#!/usr/bin/env python3
"""Build Batch 047 Brink's / CIT / KAR canonical V9 artifacts."""
from __future__ import annotations
import importlib.util, json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; ASOF="2026-09-09"
spec=importlib.util.spec_from_file_location("batch46",ROOT/"scripts/46_build_batch_046_v9.py")
m=importlib.util.module_from_spec(spec); spec.loader.exec_module(m)

m.BUSINESS.update({
"bco":"Brink's는 현금·귀중품 운송, ATM replenishment, vault, money processing, smart safe와 국제 valuables logistics를 제공한다. 경제엔진은 `stop 수×가격+고부가 서비스-노선·인력·차량·보안비-구조조정·이자·세금·capex`다. 현금 결제량이 줄어도 outsourcing 침투·가격·route density가 더 빨리 오르면 매출과 FCF는 성장할 수 있다. 따라서 cash usage보다 revenue/stop, AMS·BGS mix, local-currency margin, FCF conversion과 순부채를 본다.",
"cit":"CIT는 중견기업 대출·리스·factoring·vendor finance·항공기·철도차량 금융을 하던 비은행 금융사에서 예금기반 상업은행으로 전환했다. 현금엔진은 `earning assets×finance margin-fee·credit loss·funding cost·opex-tax·필요자본`이다. 2009에는 claim priority와 recovery, 2011에는 7% bankruptcy debt의 예금 대체, 2016에는 OneWest·aircraft sale·NOL, 2020에는 First Citizens 합병교환비율이 common 가치를 결정했다.",
"kar":"KAR(현 OPENLANE)는 institutional seller·dealer를 연결하는 도매 중고차 marketplace와 AFC floorplan finance를 운영했다. 경제엔진은 `판매차량×(buyer/seller fee+ancillary attach)+finance spread-credit loss-physical/digital cost-capex`다. 핵심 moat는 inventory와 buyer density가 만드는 conversion·price discovery다. 디지털 전환은 revenue/vehicle를 낮춰도 conversion과 contribution/transaction, capital intensity를 개선할 수 있으며 physical stranded cost 제거가 관건이다."
})
m.SOURCES.update({
"bco":[m.S("Brink's 2020 Form 10-K","https://www.sec.gov/Archives/edgar/data/78890/000007889021000014/bco-20201231.htm","SEC / Brink's","2021-02","COVID 충격·G4S·liquidity·leverage 검증"),m.S("Brink's FY2025 results","https://investors.brinks.com/news-releases/news-release-details/brinks-announces-fourth-quarter-and-full-year-2025-results/","Brink's","2026-02-26","장기 매출·margin·FCF 회복 검증")],
"cit":[m.S("CIT 2009 restructuring filing","https://www.sec.gov/Archives/edgar/data/1474176/000095012309051067/y79463exv99wt3ew1.htm","SEC / CIT","2009-11-01","70¢ 신규채권+신규 equity, old common 취소"),m.S("CIT 2009 Form 10-K","https://www.sec.gov/Archives/edgar/data/1171825/000089109210001036/e38085_10k.htm","SEC / CIT","2010-03","reorganization·fresh-start balance sheet"),m.S("CIT aircraft sale close","https://www.sec.gov/Archives/edgar/data/1171825/000117182517000042/cit-20170404x8k.htm","SEC / CIT","2017-04-04","Avolon에 $10.38bn 매각"),m.S("First Citizens–CIT close","https://newsroom.firstcitizens.com/2022-01-04-First-Citizens-Bank-Completes-Merger-With-CIT-Group","First Citizens","2022-01-04","합병 종결과 successor security")],
"kar":[m.S("KAR 2018 Form 10-K","https://www.sec.gov/Archives/edgar/data/1395942/000139594219000013/kar-20181231x10k.htm","SEC / KAR","2019-02","ADESA·IAA·AFC economics와 spin risk"),m.S("IAA separation Form 8-K","https://www.sec.gov/Archives/edgar/data/1395942/000139594219000036/kar-20190628x8k.htm","SEC / KAR","2019-06-28","IAA 분리 종결"),m.S("ADESA U.S. sale announcement","https://investors.openlane.com/news-releases/news-release-details/kar-global-sell-adesa-us-physical-auction-business-carvana-22","KAR / OPENLANE","2022-02-24","Carvana $2.2bn 매각으로 기업 perimeter 변경")]
})

def C(title,original,evidence,actual,verdict,lesson):
 return m.C(title,original,evidence,"수치·capital·catalyst가 원 horizon 안에 유지된다.","핵심 KPI가 두 분기 연속 역행하거나 capital/event gate가 실패하면 반증.",actual,verdict,lesson)
def I(**x):
 x["claims"]=[C(*z) for z in x.pop("claimdata")]; return x

IDEAS=[
I(id="d1cfc369-1bf6-491c-b398-13877c9d394d",date="2020-05-28",author="bdon99",ticker="BCO",entity="The Brink's Company",group="bco",raw_short=True,direction="Long",entry="COVID 저점(원문 exact price 미확인)",horizon="12~36개월",filename="analysis/ideas/2020/2020-05-28_BCO_long.md",link=None,desc=11928,cat=243,title="COVID 정상화·route density·smart-safe Long",verdict="생존·정상화·장기 margin thesis 성공, exact return 미검증",score=8.5,process=8.5,
summary="raw Short지만 본문은 명백한 Long이다. retail 45%·금융기관 45%·정부/기타 10% mix에서 essential retail이 방어하고 reopening이 volume을 되돌리며, 60% variable cost와 약 30% decremental margin이 street보다 충격을 작게 만든다고 봤다. $1.9bn net debt·3.0x leverage는 downside 4.5x까지 올라가도 $800m+ liquidity로 버티며 40%+ upside를 제시했다.",valuation="정상화 EBITDA×정상 EV/EBITDA에서 회복시점 순부채를 차감해야 한다. 원문은 exact target price 대신 40%+ upside를 제시했다. US margin 10%에서 Loomis 수준 13%+, BGS 15~25% margin, CompuSafe 미국 매출 $150m에서 $300m+가 bull bridge다.",actual="BCO는 2020 shock를 버텼고 retail reopening, 가격·AMS mix와 비용조정으로 실적을 회복했다. 장기적으로 매출·adjusted EBITDA가 2019 수준을 넘어섰으나 leverage와 인수통합은 계속 equity risk였다.",price="SQL performance row가 없다. exact entry와 1/3/5년 total return은 null이다.",drivers="survival liquidity, reopen volume, variable labor와 route rationalization, smart safe·cash processing outsourcing이 회복을 만들었다.",error="LatAm FX·G4S integration과 회복 지연 시 누적 순부채를 더 강하게 stress했어야 한다.",first_signal="credit-agreement leverage가 downside 4.1x를 넘거나 $800m liquidity가 두 분기 연속 감소하면 thesis break.",metrics=[("Net debt/leverage","$1.9bn/3.0x","downside 4.5x 이하","COVID 생존","성공"),("Liquidity","$800m+","회복까지 충분","자본시장 접근 유지","성공"),("US margin","10%","13%+","장기 개선","성공"),("CompuSafe US","~$150m","$300m+","AMS 성장","방향 성공"),("Upside","40%+","정상화","exact return 없음","미검증")],timeline=[("2020-02","G4S deal","leverage 증가"),("2020-05-28","VIC Long","eye-of-storm"),("2020-H2","cost action","decremental 완화"),("2021","reopening","volume 회복"),("2022","pricing/AMS","mix 개선"),("2025","margin·FCF 확대","장기 검증")],claimdata=[("reopening","cash pickup이 travel보다 빨리 회복","essential retail·sticky banks","실제 영업 회복","성공","산업별 reopen clock을 나눈다."),("liquidity","$800m+로 2020을 통과","3.0x→4.5x downside","default 없이 생존","성공","gross liquidity를 covenant와 연결한다."),("variable cost","60% variable·30% decremental","hourly labor·per-pickup","비용조정 작동","성공","route density와 가변비를 분리한다."),("cash persistence","현금은 사라지지 않는다","미국 33% 거래·LatAm 현금비중","물량감소를 가격/mix가 상쇄","성공","volume decline≠equity decline."),("smart safe","$2bn TAM·5년 recurring contract","고객 20~40% 절감","AMS 성장","성공","고객 ROI가 adoption을 만든다."),("40%+ upside","정상화와 rerating","margin·liquidity bridge","exact price 미복원","미검증","event와 return을 구분한다.")]),
I(id="f2dc229e-52b4-4b56-ae6b-ca21f91e3415",date="2009-07-28",author="Rotin",ticker="CIT",entity="CIT Group — 5.6% 2011 senior unsecured notes",group="cit",raw_short=True,direction="Long",entry="59 cents on par",horizon="6~24개월",filename="analysis/ideas/2009/2009-07-28_CIT_senior_unsecured_long.md",link=None,desc=22766,cat=201,title="59에 산 senior unsecured recovery Long",verdict="70¢ 신규 notes+equity recovery로 성공",score=9.0,process=9.5,summary="raw Short는 틀렸다. common이 아니라 5.6% 2011 senior unsecured bond를 59에 사서 liquidation 80~100 또는 prepack recovery를 노린 credit Long이다. 기업 파산여부보다 unencumbered assets와 claim waterfall이 핵심이었다.",valuation="가격 59 대비 liquidation recovery 80~100이면 coupon 전 +36~69%다. 실제 prepack consideration은 원금 $1당 약 70¢ 신규 notes와 신규 common interests였다.",actual="CIT는 Chapter 11에 들어갔지만 빠른 prepack으로 운영기업을 보존했다. old common은 취소됐고 senior unsecured는 70¢ notes와 equity를 받아 security-selection thesis가 적중했다.",price="정확한 신규 equity mark·coupon 포함 IRR은 SQL에 없어 null이다. recovery structure 기준 성공이다.",drivers="담보부 선순위 차감 뒤에도 commercial/transport assets가 unsecured recovery를 남겼고 orderly prepack이 fire-sale loss를 줄였다.",error="DIP priming·법률비·신규 equity volatility의 sensitivity는 더 필요했다.",first_signal="추가 담보설정으로 unencumbered asset coverage가 recovery 59 아래로 내려가면 exit.",metrics=[("Bond price","59","80~100 recovery","70¢ notes+equity","성공"),("Instrument","5.6% 2011 senior","unsecured recovery","old common과 분리","성공"),("Old common","residual","0 가능","취소","예상 범위"),("Plan","prepack","orderly","5주 내 exit","성공"),("IRR","미제공","높은 recovery","exact null","미검증")],timeline=[("2009-07-28","VIC debt Long","59"),("2009-07","emergency financing","runway"),("2009-11-01","Chapter 11","prepack"),("2009-12","plan effective","70¢+equity"),("2010","new CIT trade","recovery mark"),("2011","note maturity window","terminal")],claimdata=[("instrument","common이 아니라 senior debt","5.6% 2011 note","waterfall대로 회수","성공","security identity가 먼저다."),("recovery","80~100 가능","stressed asset coverage","70¢+equity","성공","확률가중 recovery를 쓴다."),("prepack","orderly restructuring","정부·채권자 유인","신속 종결","성공","파산=0이 아니다."),("asset value","book보다 collection value","factoring·transport assets","recovery 남음","성공","encumbrance를 차감한다."),("common cancellation","equity는 전손 가능","residual claim","실제 취소","적중","기업과 security를 분리한다."),("return","59 대비 convexity","80~100 thesis","exact IRR null","부분","coupon·equity mark를 잇는다.")]),
I(id="bbce234a-0f82-416d-bfcc-e20ceae4c326",date="2011-10-04",author="brook1001",ticker="CIT",entity="CIT Group Inc.",group="cit",raw_short=True,direction="Long",entry="$29",horizon="2~4년",filename="analysis/ideas/2011/2011-10-04_CIT_long.md",link=None,desc=22841,cat=155,title="post-BK funding normalization Long",verdict="deposit funding·capital return으로 성공",score=8.5,process=8.5,summary="raw Short지만 $29에 산 common Long이다. GAAP TBV의 68%, adjusted TBV의 57%, Tier 1 common 19.1%에서 7% bankruptcy debt를 예금으로 바꾸고 finance margin 1.45%를 3~4%로 정상화하는 thesis였다.",valuation="$29, 0.68x GAAP TBV·0.57x adjusted TBV. excess cash/capital과 funding-cost 하락이 EPS와 buyback을 동시에 열어 book discount를 닫는 구조다.",actual="CIT는 예금기반을 확대하고 고비용 debt를 줄였으며 buyback·사업재편을 진행했다. 2015 OneWest 인수로 funding transformation이 더 진행됐다.",price="SQL performance row가 없어 exact return은 null이나 business·valuation catalyst는 성공으로 판정한다.",drivers="liability repricing과 excess capital이 자산성장보다 큰 per-share value driver였다.",error="fresh-start marks와 legacy runoff 속도, regulator가 허용하는 capital return timing을 더 보수적으로 봐야 했다.",first_signal="deposit mix가 늘어도 all-in funding cost가 두 분기 연속 하락하지 않으면 핵심 thesis break.",metrics=[("Entry","$29","TBV rerating","사업 정상화","성공"),("P/GAAP TBV","0.68x","1.0x 접근","discount 축소","성공"),("Adjusted TBV","0.57x","capital return","buyback 진행","성공"),("Tier 1 common","19.1%","excess","규제여력","성공"),("Finance margin","1.45%","3~4%","funding 개선","성공")],timeline=[("2009-12","reorg exit","fresh start"),("2011-10-04","VIC Long","$29"),("2012","debt runoff","funding cost 하락"),("2013-14","buybacks","per-share accretion"),("2015-08","OneWest close","deposits 확대"),("2016","bank 중심 전환","thesis 성숙")],claimdata=[("TBV discount","0.57~0.68x book","$29","discount 축소","성공","book quality를 조정한다."),("funding swap","7% debt를 deposit으로","19.1% capital","비용 하락","성공","liability-side alpha다."),("margin","1.45%→3~4%","new originations","정상화","성공","asset yield와 funding을 나눈다."),("legacy runoff","저수익 assets 축소","fresh-start portfolio","재편 진행","성공","shrinkage도 가치창출 가능."),("capital return","excess capital buyback","높은 Tier 1","실행","성공","regulatory gate를 둔다."),("duration","2~4년 정상화","debt maturities","OneWest로 강화","성공","post-BK는 긴 clock이다.")]),
I(id="a8bb036d-28b6-443d-98d7-59f02969dc49",date="2016-03-03",author="abra399",ticker="CIT",entity="CIT Group Inc.",group="cit",raw_short=True,direction="Long",entry="$31.25",horizon="12~24개월",filename="analysis/ideas/2016/2016-03-03_CIT_long.md",link="https://www.valueinvestorsclub.com/idea/CIT_GROUP_INC/5340770392",desc=19416,cat=136,title="OneWest funding·aircraft separation·NOL Long",verdict="aircraft sale·simplification·최종 strategic exit로 성공",score=9.0,process=9.0,summary="raw Short지만 실제 Long이다. $31.25에서 10x 2016E EPS $3.10, 7.5x cash EPS $4.10, 0.57x book·0.65x TBV였다. OneWest $14.5bn deposits, $5bn+ NOL, Commercial Air 분리와 discount buyback으로 $40~45+를 봤다.",valuation="Commercial Air $3.0bn book에 0.9~1.0x=$13.5~15/share를 적용하면 stub은 $16~17.5, 0.4x book·0.5x TBV다. ex-air EPS $2.00/cash EPS $2.70과 NOL NPV $1~1.2bn이 추가 upside다.",actual="Commercial Air는 2017 Avolon에 $10.38bn에 매각됐고 CIT는 bank 중심으로 단순화했다. buyback과 funding 개선 뒤 2022 First Citizens와 합병했다.",price="SQL performance row가 없어 exact return은 null. $40~45+ thesis는 event와 strategic value 기준 성공이다.",drivers="숨은 aircraft value의 현금화, low-cost deposit 전환, NOL cash earnings와 discount buyback이 가치를 실현했다.",error="rail/energy·maritime credit와 Financial Freedom control weakness, NOL ownership-change haircut을 더 강하게 반영할 필요가 있었다.",first_signal="aircraft sale이 0.9x book 아래거나 CCAR가 buyback을 막고 funding cost 2.22%가 하락하지 않으면 target 하향.",metrics=[("Entry","$31.25","$40~45+","strategic value 실현","성공"),("P/B·P/TBV","0.57x/0.65x","rerating","simplification","성공"),("2016 EPS","$3.10","10x","cash earnings 우위","성공"),("NOL",">$5bn","NPV $1~1.2bn","활용","성공"),("Air assets","$10.7bn","분리","$10.38bn sale","성공")],timeline=[("2015-08","OneWest close","$14.5bn deposits"),("2016-03-03","VIC Long","$31.25"),("2016","CCAR/buyback","capital gate"),("2017-04-04","air sale close","$10.38bn"),("2020-10","FCNCA deal","terminal"),("2022-01","merger close","strategic exit")],claimdata=[("OneWest","deposit funding 개선","64% funding·2.22% cost","전환 진전","성공","deposit beta를 본다."),("air separation","$10.7bn assets monetization","0.9~1.0x book","$10.38bn sale","성공","gross와 net proceeds를 나눈다."),("stub cheapness","0.4x book·0.5x TBV","$16~17.5 implied","discount 축소","성공","residual SOTP가 핵심."),("NOL","cash EPS>GAAP","$5bn+ NOL","활용","성공","ownership-change haircut 필요."),("buyback","0.5x book에서 accretive","과거 $1.3bn","capital return","성공","share count로 검증한다."),("sale option","funding synergies가 buyer 가치","CEO 교체","First Citizens 결합","성공","strategic optionality를 수치화한다.")]),
I(id="09a5b37a-fc76-4352-83c4-4f5852b0ce1e",date="2020-10-19",author="abra399",ticker="CIT",entity="CIT Group Inc. / First Citizens merger claim",group="cit",raw_short=True,direction="Long",entry="$26.89",horizon="12~24개월",filename="analysis/ideas/2020/2020-10-19_CIT_merger_long.md",link="https://www.valueinvestorsclub.com/idea/CIT_GROUP_INC/4146606402",desc=4923,cat=72,title="0.062 FCNCA 교환비율의 merger/RemainCo Long",verdict="합병 종결·synergy 실현으로 성공",score=9.0,process=9.0,summary="raw Short지만 합병 발표 뒤 CIT common Long이다. CIT 1주가 FCNCA 0.062주를 받는 조건으로 combined bank를 약 6.2x pro forma EPS와 94% pro forma TBV에 사며 cost saves와 CIT deposit cost 하락을 옵션으로 봤다.",valuation="$26.89 entry. 교환비율 0.062×FCNCA price로 deal value를 계산하고, pro forma EPS 6.2x·TBV 0.94x에서 비용·funding synergy를 더했다. 핵심은 headline premium보다 successor FCNCA의 per-share earnings다.",actual="거래는 규제승인을 거쳐 2022-01-03 완료됐고 CIT는 First Citizens에 흡수됐다. 법인·funding·cost base가 합쳐지며 standalone thesis는 successor security로 전환됐다.",price="SQL performance row가 없어 exact hedge/total return은 null. deal completion 기준 성공이다.",drivers="낮은 implied combined-bank multiple, 중복비용 제거와 First Citizens의 낮은 funding cost가 수익원이었다.",error="긴 규제기간, FCNCA stock beta와 unhedged market risk, integration credit marks를 더 명시해야 했다.",first_signal="교환비율은 고정인데 FCNCA price가 하락하거나 규제 closing clock이 2021년을 넘기면 expected IRR 재산정.",metrics=[("Entry","$26.89","deal value","합병 종결","성공"),("Exchange","0.062 FCNCA","고정","실행","성공"),("Pro forma P/E","6.2x","rerating","successor 성장","성공"),("P/TBV","~0.94x","1x+","결합","성공"),("Close","예정","규제승인","2022-01-03","성공")],timeline=[("2020-10-16","deal 발표","all-stock"),("2020-10-19","VIC Long","$26.89"),("2021","regulatory review","duration"),("2021-12","승인","closing gate"),("2022-01-03","법적 close","CIT 종료"),("2022+","integration","successor payoff")],claimdata=[("exchange value","0.062 FCNCA","fixed ratio","그대로 실행","성공","successor price를 잇는다."),("cheap combined bank","6.2x EPS","pro forma earnings","결합 완료","성공","merger accounting을 조정한다."),("TBV","94% pro forma","book 보호","strategic scale","성공","credit mark 후 TBV를 본다."),("cost saves","중복비용 제거","두 은행 platform","integration 진행","성공","gross synergy와 cost-to-achieve 분리."),("funding","CIT deposit cost 하락","FCNCA franchise","결합으로 현실화","성공","liability synergy가 핵심."),("closing","regulatory completion","all-stock structure","2022 close","성공","probability×duration으로 IRR 계산.")]),
]

def kar(iid,date,author,entry,title,summary,valuation,actual,verdict,metrics,timeline,desc,cat,link=None):
 return I(id=iid,date=date,author=author,ticker="KAR",entity="KAR Auction Services / ADESA",group="kar",raw_short=(date<"2019-01-01"),direction="Long",entry=entry,horizon="12~36개월",filename=f"analysis/ideas/{date[:4]}/{date}_KAR_long.md",link=link,desc=desc,cat=cat,title=title,verdict=verdict,score=8.0,process=8.5,summary=summary,valuation=valuation,actual=actual,price="SQL performance row가 없어 exact 1/3/5년 return은 null이다.",drivers="marketplace liquidity, conversion, ancillary attach, FCF와 portfolio action이 실제 payoff를 만들었다.",error="cycle volume과 structural digital change, gross sale value와 equity proceeds를 더 엄격히 분리할 필요가 있었다.",first_signal="conversion·contribution/vehicle가 두 분기 연속 하락하거나 digital cost 절감보다 fee 감소가 크면 thesis break.",metrics=metrics,timeline=timeline,claimdata=[("volume/conversion","공급과 sell-through 회복","차량·conversion data","cycle별 혼합","부분~성공","volume과 conversion을 나눈다."),("network moat","buyer density가 pricing을 지지","oligopoly share","시장지위 유지","성공","liquidity가 moat다."),("ancillary","fee/vehicle와 attach 증가","inspection·transport·reconditioning","unit revenue 확대","성공","GMV보다 contribution이다."),("digital","online 전환이 가치창출","낮은 cost-to-serve","business perimeter 변화","혼합","stranded cost를 차감한다."),("capital allocation","FCF·spin/sale가 equity로 귀속","buyback·debt·SOTP","event 발생","부분~성공","net proceeds를 계산한다."),("valuation",title,entry,"exact return null","미검증", "target과 total return을 분리한다.")])

IDEAS += [
kar("dfbba713-4d92-41d8-8877-b842d7ca966c","2006-09-13","glg919","$22.79","$29~35 ADESA normalization Long","raw Short지만 실제 Long. 1.9m vehicles, $425~450 blended revenue/transaction, 25%+ auction EBITDA margin과 AFC dealer-finance flywheel을 샀다. conversion 58.2%의 일시부진이 62%+로 정상화되고 200~300bp margin expansion을 기대했다.","2008 EBITDA $330m-maintenance capex $40m=$290m에 9~11x, 순부채 0을 적용해 $29~35, base $32다.","2007 private-equity consortium이 ADESA를 인수하면서 value가 현금화됐다. deal price는 full bull보다 낮아도 event Long은 성공했다.","takeout으로 성공",[("Entry","$22.79","$29~35","takeout","성공"),("Volume","1.9m","증가","deal 전 franchise","성공"),("Conversion","58.2%","62%+","정상화 기대","부분"),("EBITDA","$280m→$330m","2008","takeout 선행","미검증"),("FCF",">$100m/yr","net debt 0","buyer 가치","성공")],[("2004","ALLETE spin","standalone"),("2006-09-13","VIC Long","$22.79"),("2006-Q2","conversion 58.2%","기회"),("2007","buyout 발표","catalyst"),("2007","거래 종결","takeout"),("2009","KAR 재상장","successor")],16621,216),
kar("2d4fcc5e-7280-498f-aa1f-b7d51b3b9b7a","2010-11-12","can869","post-IPO price(원문 미복원)","$500m FCF·deleveraging recovery Long","raw Short지만 catalyst는 2.5년 $500m FCF, 단기 repossession 감소 이후 multiple expansion을 말하는 Long이다. auction·AFC cash flow로 LBO debt를 줄여 equity claim을 키우는 구조다.","2.5년 $500m FCF가 당시 market cap의 약 30%라는 anchor다. normalized EBITDA에서 debt를 차감해 deleveraging convexity를 본다.","KAR는 FCF·deleveraging을 이어가며 public auction platform으로 성장했고 이후 IAA 분리까지 갔다. exact return은 미복원이다.","business/deleveraging 성공, exact return 미검증",[("FCF","$500m/2.5y","30% market cap","현금창출 지속","성공"),("Debt","LBO leverage","감소","deleveraging","성공"),("Repo volume","단기 감소","정상화","cycle 혼합","부분"),("Auction moat","ADESA/IAA","유지","분리까지 성장","성공"),("Return","미복원","rerating","null","미검증")],[("2009","KAR IPO","LBO exit"),("2010-11-12","VIC Long","FCF thesis"),("2011-12","Openlane deal","digital"),("2012-13","deleveraging","equity accretion"),("2018","IAA spin 발표","SOTP"),("2019-06","spin 완료","terminal checkpoint")],0,236,"https://www.valueinvestorsclub.com/idea/KAR_AUCTION_SERVICES_INC/5012749624"),
kar("93acf9c9-943b-4f47-a530-c7fe355e48bb","2018-08-01","VIC_Member2015","약 $59","IAA spin SOTP $83 Long","raw Short지만 실제 Long. ADESA 28% whole-car share, IAA/Copart 각 40% salvage, AFC를 분리해 IAA spin과 TradeRev digital option을 샀다. $83 target, 약 40% upside다.","ADESA 11x NTM EBITDA, IAA 17x를 적용해 $83. IAA는 Copart 26.6x P/E 대비 할인, ADESA online은 80% margin과 70%+ OEM white-label share를 근거로 했다.","IAA spin은 2019-06-28 완료돼 SOTP catalyst가 정확히 실현됐다. 이후 ADESA physical business 매각으로 remainco perimeter가 다시 변했다.","spin catalyst 성공, 장기 remainco 경로 혼합",[("Target","$83","+40%","spin 완료","사건 성공"),("IAA share","~40%","Copart comp","독립 상장","성공"),("ADESA share","28%","digital 방어","physical sale","혼합"),("Online margin","80%","mix 개선","digital 확대","성공"),("TradeRev","D2D option","adoption","후속 손실","혼합")],[("2017-10","TradeRev 100%","digital bet"),("2018-02","IAA spin 발표","SOTP"),("2018-08-01","VIC Long","$83"),("2019-06-28","spin 완료","핵심 catalyst"),("2020","COVID/digital","경로변화"),("2022","ADESA U.S. sale","perimeter reset")],12379,23),
kar("f8f8e751-81f4-4429-bced-42c98e351b8c","2019-03-04","nychrg","spin 전 KAR price(원문 미복원)","IAA spin·양쪽 multiple unlock Long","raw와 실제 모두 Long. private-letter ruling과 IAA spin 완료, 이후 IAA와 ADESA remainco의 독립 실행으로 conglomerate discount가 줄어드는 event trade다.","IAA에는 Copart 계열 premium, remainco에는 normalized marketplace/FCF multiple을 적용하고 dis-synergy·debt를 차감해야 한다.","private-letter ruling 뒤 IAA 분리는 2019-06-28 완료됐다. event는 성공했지만 이후 COVID·ADESA sale로 장기 기업경로가 달라졌다.","spin event 성공, exact return 미검증",[("PLR","대기","수령","spin 진행","성공"),("IAA spin","예정","완료","2019-06-28","성공"),("Dis-synergy","minimal","관리","독립회사","부분"),("RemainCo","ADESA/AFC","rerating","후속 sale","혼합"),("Return","미복원","SOTP unlock","null","미검증")],[("2018-02","spin 발표","event"),("2019-03-04","VIC Long","PLR"),("2019-Q2","PLR/filing","gate"),("2019-06-28","IAA 분리","성공"),("2020","COVID","digital acceleration"),("2022","ADESA sale","새 thesis")],0,157,"https://www.valueinvestorsclub.com/idea/KAR_AUCTION_SERVICES_INC/5257676092"),
kar("bbc0e4a7-71df-4431-a0fe-290847632214","2019-11-20","Fletch","spin 후 price(원문 미복원)","$28~30 TradeRev turnaround Long","raw와 실제 모두 Long. IAA 분리 후 pure-play ADESA/AFC에서 TradeRev FY18 -$53m·FY19 -$60m 손실이 2021 breakeven으로 전환되고 physical revenue/vehicle $893 중 약 $600 ancillary, COTW 유럽 확장이 margin을 회복한다고 봤다.","ex-TradeRev 2020 EBITDA 8.5x·FCF 13x에 TradeRev $250m을 더해 $28, 실행 시 $30+다.","COVID가 digital adoption을 가속했지만 TradeRev 자체 breakeven timing과 physical economics는 흔들렸다. 2022 ADESA U.S. physical business $2.2bn sale로 원 forecast perimeter가 사라졌다.","digital 방향 적중, TradeRev timing·standalone target 혼합",[("Target","$28/$30+","8.5x EBITDA","perimeter 변경","혼합"),("TradeRev loss","-$60m","2021 breakeven","지연/통합","실패"),("Physical rev/car","$893","ancillary 유지","asset sale","혼합"),("COTW","유럽 진입","성장","OPENLANE 축","성공"),("ADESA sale","미가정","standalone compound","$2.2bn sale","경로변경")],[("2019-06","IAA spin","pure-play"),("2019-11-20","VIC Long","$28 target"),("2020","COVID","digital acceleration"),("2021","TradeRev BE 목표","지연"),("2022-05","ADESA sale close","$2.2bn"),("2023","OPENLANE rebrand","digital perimeter")],7964,61)
]

def payload(ideas):
 p=m.make_payload(ideas); p["batch"]=47; p["title"]="Brink's / CIT / KAR — Direction, Security, Funding and Marketplace V9"; return p
def index(ideas):
 rows=[]
 for n,i in enumerate(ideas,1):
  raw="Short" if i["raw_short"] else "Long"; link=Path(i["filename"]).relative_to("analysis")
  rows.append(f"| {n} | {i['date']} | {i['entity']} | {raw}→**{i['direction']}** | {i['verdict']} | [{i['title']}]({link}) |")
 return "\n".join(["# Batch 047 — Brink's / CIT / KAR — V9 Index","",f"> Research as-of {ASOF}. 첨부 SQL 원문으로 10건의 entity·direction·security를 수동 감사했다.","","## 0. 배치 결론","","raw Short 8건 중 실제 Short는 0건이다. BCO는 COVID recovery common Long, CIT 2009는 senior-unsecured debt Long, 나머지는 common/merger Long이다. CIT는 `recovery→funding normalization→asset separation→strategic merger`, KAR는 `physical liquidity→deleveraging→spin→digital/perimeter reset`의 lifecycle로 읽는다.","","## 1. Idea Units","","| # | 날짜 | 실제 security/entity | raw→연구 방향 | 판정 | Canonical report |","|---:|---|---|---|---|---|",*rows,"","## 2. 공통 투자교훈","","1. **Security가 기업보다 먼저다.** CIT 2009 common은 0이지만 senior debt는 recovery가 있었다.\n2. **Funding normalization은 liability-side alpha다.** post-BK lender는 asset growth보다 조달비용이 중요하다.\n3. **Spin 성공과 remainco 성공은 다르다.** IAA 분리 뒤 ADESA perimeter가 다시 바뀌었다.\n4. **Digital cannibalization은 contribution으로 본다.** revenue/vehicle보다 conversion·cost-to-serve·stranded cost가 핵심이다.\n5. **쇠퇴산업도 equity는 성장할 수 있다.** BCO는 volume 감소를 pricing·outsourcing·density로 상쇄했다.\n6. **성과가 없으면 null이다.** corporate event를 임의 return으로 바꾸지 않는다.","","## 3. 산출물","","- Payload: `data/curated/batch_047_brinks_cit_kar_deep_v7.json`\n- Wrapper: `analysis/batch_047_brinks_cit_kar_10.md`\n- Builder: `scripts/47_build_batch_047_v9.py`",""])

def main():
 ideas=IDEAS
 assert len(ideas)==10 and len({i['id'] for i in ideas})==10
 for i in ideas:
  assert len(i['claims'])==6 and len(i['metrics'])==5 and len(i['timeline'])>=6
  p=ROOT/i['filename']; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(m.report(i),encoding='utf-8')
 parts=[str(Path(i['filename']).relative_to('analysis')) for i in ideas]
 (ROOT/'analysis/batch_047_brinks_cit_kar_10.md').write_text("# Batch 047 — Brink's / CIT / KAR V9\n\n<!-- batch_parts: "+'|'.join(parts)+" -->\n",encoding='utf-8')
 (ROOT/'analysis/batch_047_v9_index.md').write_text(index(ideas),encoding='utf-8')
 (ROOT/'data/curated/batch_047_brinks_cit_kar_deep_v7.json').write_text(json.dumps(payload(ideas),ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 packet={"batch":"047","record_count":10,"source":"VIC_IDEAS(4).sql","direction_audit":"complete","performance_rule":"no SQL performance rows; exact returns null","candidates":[{"idea_id":i['id'],"date":i['date'],"ticker":i['ticker'],"company_name":i['entity'],"author":i['author'],"raw_direction":"Short" if i['raw_short'] else "Long","research_direction":i['direction'],"canonical_report":i['filename']} for i in ideas]}
 (ROOT/'data/curated/batch_047_source_packet.json').write_text(json.dumps(packet,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 print({k:len(payload(ideas)[k]) for k in ('ideas_master','postmortems','sections','claims','metrics','timeline','sources')})
if __name__=='__main__': main()
