#!/usr/bin/env python3
"""Build Batch 048 KAR / Time Warner / Metals USA canonical V9 artifacts."""
from __future__ import annotations

import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASOF = "2026-09-10"
spec = importlib.util.spec_from_file_location("batch46", ROOT / "scripts/46_build_batch_046_v9.py")
m = importlib.util.module_from_spec(spec)
spec.loader.exec_module(m)
m.ASOF = ASOF

m.BUSINESS.update({
    "kar48": "KAR Auction Services(현 OPENLANE)는 OEM·리스/렌터카·금융사·fleet·딜러가 내놓은 중고차를 매입 딜러에게 연결하는 도매 remarketing marketplace와 AFC floorplan finance를 운영했다. 경제엔진은 `거래대수×(buyer/seller fee+inspection·reconditioning·transport attach)+AFC spread-credit loss-physical/digital cost-capex`다. 재고위험은 낮지만 seller mix, conversion, revenue per unit와 고정 경매장 비용 때문에 volume leverage가 크다. 디지털 전환의 성패는 온라인 비중이 아니라 contribution/vehicle, buyer liquidity, ancillary attach, customer acquisition cost와 physical stranded cost를 합쳐 판단해야 한다.",
    "twx": "Time Warner는 시기별로 TWC·AOL·Time Inc.를 분리하고 최종적으로 Turner, HBO, Warner Bros.의 premium-content 기업이 됐다. 현금엔진은 `Turner affiliate fee·광고 + HBO 구독·라이선스 + Warner Bros. 영화·TV·게임 수익 - 스포츠/제작비·마케팅·corporate cost·이자·세금`이다. OTT는 cable bundle과 linear viewing에는 위협이지만 premium IP에는 신규 buyer·DTC 경로를 늘릴 수 있다. 따라서 가입가구·affiliate fee, 광고, content spend/rights, HBO subs/ARPU, library monetization, FCF·buyback과 strategic control premium을 분리한다.",
    "metalsusa": "2003년 Metals USA는 철강 mill이 아니라 coil·plate·비철 소재를 slitting, blanking, leveling, cut-to-length, laser cutting 등으로 가공·유통하는 metal service center였다. 경제엔진은 `처리 tonnage×금속 spread·가공 fee-inventory holding loss-SG&A-capex-interest-tax`이며, 운전자본이 매출의 큰 비중을 차지해 inventory turns·receivable collection·supplier terms가 EBITDA만큼 중요하다. Chapter 11 뒤 debt-to-equity 전환, 새 운영자, working-capital release와 steel cycle 회복이 동시에 common equity convexity를 만들었다."
})

m.SOURCES.update({
    "kar48": [
        m.S("KAR 2020 Form 10-K", "https://www.sec.gov/Archives/edgar/data/1395942/000139594221000006/kar-20201231.htm", "SEC / KAR", "2021-02-24", "BacklotCars·AFC·COVID 비용구조와 digital 전환"),
        m.S("KAR $550m strategic investment", "https://www.sec.gov/Archives/edgar/data/1395942/000114036120012558/nc10012306x1_ex99-1.htm", "SEC / KAR", "2020-05-26", "Apax/Periphas preferred와 liquidity de-risk"),
        m.S("ADESA U.S. sale completion", "https://ir.corporate.openlane.com/investor-relations/investor-news/press-release-details/2022/KAR-Global-Completes-Sale-of-ADESA-US-Physical-Auction-Business-to-Carvana/default.aspx", "KAR / OPENLANE", "2022-05-10", "56개 미국 physical logistics center 매각과 digital perimeter"),
        m.S("OPENLANE corporate site", "https://corporate.openlane.com/", "OPENLANE", "2023-2026", "KAR Global의 digital marketplace 정체성과 후속 사업범위")
    ],
    "twx": [
        m.S("Time Warner 2007 Form 10-K", "https://www.sec.gov/Archives/edgar/data/1105705/000095014408001291/g11419e10vk.htm", "SEC / Time Warner", "2008-02-29", "2007 주가범위·TWC/AOL과 사업구조"),
        m.S("TWC separation disclosure", "https://www.sec.gov/Archives/edgar/data/1105705/000095014409003643/g18170e10vq.htm", "SEC / Time Warner", "2009-03", "$9.253bn cash transfer와 TWC 분리"),
        m.S("Time Warner 2015 Form 10-K", "https://www.sec.gov/Archives/edgar/data/1105705/000119312516477965/d280491d10k.htm", "SEC / Time Warner", "2016-02-24", "Turner·HBO·Warner Bros. segment economics"),
        m.S("Time Warner 2016 Form 10-K", "https://www.sec.gov/Archives/edgar/data/1105705/000119312517053483/d300508d10k.htm", "SEC / Time Warner", "2017-02-22", "2016 EPS·OTT·AT&T collar와 year-end 2017 예상"),
        m.S("DOJ antitrust challenge", "https://www.justice.gov/archives/opa/pr/justice-department-challenges-attdirectv-s-acquisition-time-warner", "U.S. DOJ", "2017-11-20", "vertical deal에 대한 소송과 duration risk"),
        m.S("AT&T closing Form 8-K", "https://www.sec.gov/Archives/edgar/data/732717/000119312518194502/d609728d8k.htm", "SEC / AT&T", "2018-06-15", "$53.75 cash+1.437 AT&T shares의 최종 consideration")
    ],
    "metalsusa": [
        m.S("Metals USA acquisition completion", "https://www.sec.gov/Archives/edgar/data/1038363/000119312505235953/dex99a9.htm", "SEC / Metals USA", "2005-11-30", "Apollo affiliate의 $22 cash/share 인수 완료"),
        m.S("Metals USA transaction materials", "https://www.sec.gov/Archives/edgar/data/1038363/000119312505124774/dex99c5.htm", "SEC / Metals USA", "2005-06", "merger consideration·거래 배경"),
        m.S("Metals USA post-transaction filing", "https://www.sec.gov/Archives/edgar/data/1038363/000119312508034594/d10k.htm", "SEC / Metals USA", "2008-02", "$22 cash merger와 기업 연속성")
    ]
})

PERF = {
    "ffa62e3d-8c80-4064-b37b-f81dd52825cb": {"1m": 0.8556962025, "3m": 1.1056962025, "6m": 1.1424050633, "1y": 1.1639240506, "2y": 1.0531645570},
    "7f2bf8af-02a4-4335-80de-5ab1a702a9ef": {"1m": 1.0401197605, "3m": 0.9107784431, "6m": 0.9239520958, "1y": 1.0089820359}
}

def C(title, original, evidence, actual, verdict, lesson):
    return m.C(title, original, evidence, "핵심 수치·capital·catalyst가 원 horizon 안에 유지된다.", "핵심 KPI가 두 분기 연속 역행하거나 event gate가 실패하면 반증한다.", actual, verdict, lesson)

def I(**idea):
    idea["claims"] = [C(*row) for row in idea.pop("claimdata")]
    return idea

IDEAS = [
I(id="ffa62e3d-8c80-4064-b37b-f81dd52825cb",date="2020-06-03",author="Flat Iron",ticker="KAR",entity="KAR Auction Services",group="kar48",raw_short=True,direction="Long",entry="$15.80",horizon="12~18개월",filename="analysis/ideas/2020/2020-06-03_KAR_long.md",link="https://www.valueinvestorsclub.com/idea/KAR_AUCTION_SERVICES_INC/9473876793",desc=9098,cat=126,title="preferred 자본·거래량 정상화·비용 reset Long",verdict="부분 성공 — survival·volume 회복은 적중, +40% rerating은 미달",score=7.0,process=8.0,
summary="raw Short지만 실제 common Long이다. COVID로 74개 physical location이 멈추고 cash burn이 주당 $25~30m까지 커졌지만, 5월 중순 거래량은 45~50k vehicles/week로 회복했다. Apax/Periphas의 $550m perpetual convertible preferred가 distress tail을 줄인 뒤 2021 EBITDA 정상화와 영구 비용절감, 8~8.5x valuation으로 약 20~40% upside를 기대했다.",
valuation="$15.80에서 downside는 과거 2020 EBITDA guide 중간값을 2021에 회복하고 8x를 적용해 약 +20%, base는 비용절감으로 guide를 웃돌고 8.5x를 적용해 약 +40%였다. Preferred의 conversion·dividend와 working-capital 재흡수, 회복 시점 순부채를 차감해야 한다. 정상 EBITDA와 정상 multiple을 동시에 회복시키는 이중 가정이 가장 큰 민감도다.",
actual="$550m 자본은 유동성 tail risk를 실질적으로 줄였고 거래량도 trough에서 회복했다. 회사는 BacklotCars를 인수하고 digital marketplace로 이동했다. 그러나 2022년 ADESA U.S. physical business를 매각하면서 종착점은 과거 physical margin 복원보다 portfolio 재구성에 가까웠다.",
price="보존된 price multiplier 기준 1M -14.4%, 3M +10.6%, 6M +14.2%, 1Y +16.4%, 2Y +5.3%다. 이는 배당·preferred dilution을 제외한 price-only 결과다. 생존 논지는 맞았지만 원문의 easy +40%에는 못 미쳤다.",drivers="초기 수익은 $550m 자본으로 생존확률이 상승하고 거래량이 정상화한 데서 나왔다. 제한요인은 preferred dilution, 낮은 ancillary revenue, digital 투자와 사업 perimeter 변화였다. survival trade와 정상 multiple trade는 별개였다.",error="preferred를 gross debt와 거의 상계하고 2021 EBITDA와 8.5x multiple을 동시에 정상화했다. 영구 비용절감이 fee/RPU 하락과 digital 투자비를 얼마나 상쇄하는지 별도 bridge가 부족했다.",first_signal="volume이 회복돼도 RPU·ancillary attach가 정상화되지 않거나 diluted leverage가 3.5x covenant 경로로 내려오지 않으면 +40% base case를 제거해야 했다.",
metrics=[("Entry/target","$15.80","+20~40%","1Y +16.4%·2Y +5.3%","부분 실패"),("Liquidity injection","$550m preferred","distress tail 제거","생존·운영 지속","성공"),("Weekly volume","20k breakeven→45~50k","정상화","회복","성공"),("Leverage","3.8x","3.0x 접근","asset sale 포함 경로변경","혼합"),("Business perimeter","74 physical sites","hybrid margin 개선","2022 U.S. physical sale","경로변경")],timeline=[("2020-03","physical shutdown·cash burn","distress"),("2020-05-26","$550m preferred 발표","liquidity de-risk"),("2020-06-03","VIC Long $15.80","recovery clock"),("2020-11","BacklotCars 인수","digital 투자"),("2021","volume·업황 정상화","survival 확인"),("2022-05-10","ADESA U.S. physical sale 완료","perimeter 변경"),("2023","OPENLANE rebrand","digital 종착점")],
claimdata=[("survival tail 제거","$550m preferred로 distress 가능성이 크게 낮아진다.","conversion $17.75·covenant holiday·2024년 전 큰 만기 없음","default 없이 운영을 지속했다.","성공","유동성 거래와 rerating 거래를 분리한다."),("volume normalization","lockdown trough의 1m annualized run-rate가 정상화된다.","5월 중순 45~50k vehicles/week","거래량이 회복됐다.","성공","주가보다 weekly throughput을 먼저 본다."),("영구 비용절감","furlough·digitalization이 overhead를 낮춘다.","70%+ furlough·20k/week breakeven","cost base는 낮아졌지만 digital 투자도 늘었다.","부분 성공","gross cost-out에서 성장투자를 차감한다."),("RPU/ancillary 회복","물리서비스 재개로 약 $450 RPU가 정상화된다.","auction fee 45%·ancillary 55%","service mix와 perimeter가 바뀌었다.","혼합","volume과 contribution/vehicle를 함께 본다."),("8~8.5x 정상 multiple","정상 EBITDA가 돌아오면 20~40% 오른다.","역사적 9~11x 아래 valuation","1Y +16.4%로 full rerating은 미달했다.","부분 실패","EBITDA와 multiple 동시 정상화를 stress한다."),("hybrid auction moat","physical network와 online이 함께 moat가 된다.","74 sites·buyer liquidity·AFC","U.S. physical sites를 매각하고 digital 집중했다.","경로변경","moat의 소유자가 토지인지 customer graph인지 묻는다.")]),

I(id="7f2bf8af-02a4-4335-80de-5ab1a702a9ef",date="2021-07-23",author="humkae848",ticker="KAR",entity="KAR Auction Services",group="kar48",raw_short=True,direction="Long",entry="$16.70 next-day close",horizon="3년",filename="analysis/ideas/2021/2021-07-23_KAR_long.md",link=None,desc=35906,cat=121,title="digital wholesale marketplace·2024 SOTP Long",verdict="실패/경로변경 — digital 방향은 맞았지만 2024 forecast object가 소멸",score=5.5,process=8.0,
summary="raw Short지만 실제 common Long이다. COVID가 5,000명·$150m+ 영구 비용절감과 100% online bidding을 앞당겼고, commercial consignor workflow·AFC·Openlane이 ACV식 앱의 침투를 방어한다고 봤다. BacklotCars가 2~5m dealer-to-dealer TAM을 열어 2024 revenue $2.65bn, EBITDA $585m·22% margin, 9x와 $27~30 fair value를 만들 것으로 기대했다.",
valuation="2024 ADESA 3.7m units×RPU $540에서 EBITDA $420m, AFC $165m으로 consolidated $585m을 만들고 blended 9x를 적용했다. Upside는 BacklotCars 800k units×$400 RPU×25% margin=$80m EBITDA에 15x를 별도 적용했다. 옛 physical EBITDA 정상화와 새 digital multiple을 동시에 더하고 기업 perimeter가 고정된다는 가정이 약점이다.",
actual="BacklotCars·CARWAVE·OPENLANE는 전략의 중심이 됐다. 그러나 2022년 KAR은 ADESA U.S. physical auction sites·operations·staff 56개 거점을 Carvana에 팔았다. commercial relationship과 일부 digital/private-label platform은 남았지만 2024 ADESA/AFC SOTP를 동일 basis로 검증할 대상은 사라졌다.",
price="보존 price multiplier 기준 1M +4.0%, 3M -8.9%, 6M -7.6%, 1Y +0.9%다. 2~3년 series는 없어 3년 목표 IRR은 계산하지 않는다. 1년 rerating은 사실상 없었고 이후 기업 perimeter가 바뀌었다.",drivers="digital workflow와 customer graph에 대한 통찰은 맞았지만 주가 수익은 고정된 2024 SOTP가 아니라 capital allocation과 physical asset sale 조건에 종속됐다. 높은 run-rate EBITDA와 BacklotCars multiple을 함께 얹은 forecast stacking이 upside를 과장했다.",error="commercial moat를 physical service network와 customer relationship 중 어디에 귀속할지 명확히 하지 않았다. BacklotCars CAC·retention·통합비를 빼지 않고 15x를 적용했고, 핵심 자산 매각 시 pro-forma bridge를 두지 않았다.",first_signal="2022년 ADESA U.S. physical sale 발표가 가장 명확한 thesis break다. 그 시점부터 2024 $585m EBITDA·$27~30 target을 폐기하고 net proceeds와 잔존 디지털 business를 새로 평가해야 했다.",
metrics=[("Entry/fair value","$16.70","$27~30","1Y +0.9%","실패"),("2024 EBITDA","$375m 2020","$585m·22% margin","perimeter 변경","검증 불가"),("ADESA units/RPU","3.7m/$540 E","$420m EBITDA","U.S. physical sale","모델 소멸"),("BacklotCars","200k+ 2020 units","800k·$80m EBITDA","digital 통합 지속","방향 성공"),("AFC","$2bn loans·500~600bp spread","$165m EBITDA","잔존 franchise","부분 성공")],timeline=[("2020-11","BacklotCars 인수","D2D 확장"),("2021-03","Peter Kelly CEO","execution reset"),("2021-07-23","VIC Long","$27~30·3년"),("2022-02","ADESA U.S. sale 발표","모델 break"),("2022-05-10","56개 site 매각 완료","perimeter 소멸"),("2022","CARWAVE·BacklotCars 통합","digital consolidation"),("2023","OPENLANE rebrand","digital-first 확정")],
claimdata=[("permanent cost reset","$150m+ 비용절감이 volume 정상화 때 22% margin을 만든다.","5,000명 감소·100% digital bidding","비용은 낮아졌지만 비교 perimeter가 사라졌다.","부분 성공","동일 perimeter의 unit economics로 검증한다."),("commercial consignor moat","inspection·title·logistics workflow가 digital entrant를 막는다.","ADESA GP 약 75% commercial 추정","customer relationship은 남았지만 sites는 매각됐다.","부분 성공","서비스 자산과 고객 graph의 moat를 분리한다."),("BacklotCars TAM","2~5m D2D 시장의 digitalization이 신규 volume이다.","앱 거래는 기존 auction 외 물량도 유입","digital 전략은 확대됐다.","방향 성공","TAM보다 cohort contribution을 본다."),("2024 $585m EBITDA","ADESA $420m+AFC $165m을 달성한다.","3.7m units·$540 RPU·22% margin","자산 매각으로 forecast object가 소멸했다.","검증 불가","perimeter change는 새 모델을 요구한다."),("9x·$27~30","niche marketplace multiple로 rerate한다.","peer 8~22x·KAR 6.4x run-rate","1Y +0.9%로 gap이 닫히지 않았다.","실패","peer multiple보다 현금귀속을 본다."),("strategic/PE optionality","2년 spin 제한 뒤 corporate action이 downside를 막는다.","Apax preferred·과거 PE ownership","회사 매각 대신 핵심 asset sale이 일어났다.","경로변경","optional event의 형태별 payoff를 나눈다.")]),

I(id="34b54ac6-6f41-4576-845b-4cfa4bb30646",date="2006-01-31",author="beech625",ticker="TWX",entity="Time Warner Jan-2008 $15 calls",group="twx",raw_short=True,direction="LEAPS Long",entry="common $17.50 / option $4.20",horizon="Jan-2008 expiry",filename="analysis/ideas/2006/2006-01-31_TWX_leaps_long.md",link="https://www.valueinvestorsclub.com/idea/Time_Warner_LEAPS/5456777628",desc=0,cat=213,title="conglomerate unlock의 Jan-2008 LEAPS Long",verdict="실패 — corporate 방향은 맞았지만 option clock이 먼저 만료",score=4.0,process=7.0,
summary="raw Short지만 실제 증권은 Jan-2008 $15 call Long이다. common $17.50, premium $4.20, 만기 breakeven $19.20에서 $12.5bn buyback, TWC value separation, AOL 재편과 Icahn activism을 레버리지했다. common $23.40이면 option 약 2배, $27.60이면 약 3배라는 payoff였다.",
valuation="만기 intrinsic은 `max(TWX-$15,0)`, 손익은 intrinsic-$4.20이다. $19.20 breakeven, $23.40 2배, $27.60 3배다. SOTP가 $26~28이어도 board·tax·financing 절차가 만기 뒤면 옵션은 실패한다. 기업가치 duration과 증권 duration을 같은 확률분포로 연결해야 했다.",
actual="대규모 buyback과 사업 단순화 방향은 진행됐고 TWC는 2009년 3월, AOL은 2009년 12월 분리됐다. 그러나 Time Warner 2007 연중 high는 $23.15로 2배 threshold $23.40에도 못 미쳤고 2007년말 $16.51은 breakeven 아래였다. 옳은 corporate event가 옵션 만기 뒤 왔다.",price="정확한 2008-01 option settlement·중간매도는 미복원이라 IRR은 null이다. 2007 high와 year-end close를 기준으로 원문의 2배/3배 조건은 실패했으며 security-level verdict는 실패다.",drivers="TWC/AOL 분리는 장기 enterprise value를 드러냈지만 2년 안의 주가·변동성·time decay가 option payoff를 지배했다. 값싼 implied volatility가 catalyst timing risk를 보상하지 못했다.",error="Icahn SOTP와 planned buyback을 만기 안 catalyst처럼 취급했다. legal separation calendar, 금융위기·sentiment branch와 만기 롤 비용을 확률가중하지 않았다.",first_signal="2007년 내내 common이 $23.40을 넘지 못하고 12월말 $16.51로 내려갔을 때 corporate thesis와 무관하게 option thesis를 종료해야 했다.",
metrics=[("Common/option","$17.50/$4.20","$23.40~27.60","2007 high $23.15","실패"),("Expiry breakeven","$19.20","초과","2007 year-end $16.51","실패"),("Buyback","$12.5bn","per-share accretion","실행 방향","부분 성공"),("TWC separation","촉매","만기 전","2009-03","horizon 실패"),("AOL action","재편 기대","value unlock","2009-12 spin","장기 성공")],timeline=[("2006-01-31","VIC LEAPS Long","2년 clock"),("2006~07","buyback·activism","일부 촉매"),("2007","high $23.15","2배 threshold 미달"),("2007-12-31","close $16.51","breakeven 하회"),("2008-01","option expiry","security failure"),("2009-03","TWC separation","too late"),("2009-12","AOL spin","corporate simplification")],
claimdata=[("TWC hidden value","cable asset 분리가 discount를 줄인다.","TWC public value·Icahn SOTP","2009년에 실제 분리됐다.","장기 성공/horizon 실패","spin feasibility와 만기를 연결한다."),("buyback accretion","$12.5bn repurchase가 주당가치를 빠르게 올린다.","대규모 이사회 승인","실행됐지만 option hurdle을 넘기지 못했다.","부분 성공","발표보다 평균 매입가·share count를 본다."),("AOL turnaround","광고·Google 관계가 access decline을 상쇄한다.","access/advertising 분리 가능성","turnaround보다 2009 spin으로 해결됐다.","부분 실패","문제자산의 개선과 제거를 구분한다."),("sentiment mean reversion","traditional media multiple이 정상화한다.","낮은 주가·activism","구조변화와 2007 risk-off가 막았다.","실패","sentiment catalyst에 기한을 둔다."),("cheap volatility","낮은 IV가 LEAPS convexity를 싸게 만든다.","$4.20 premium","time decay가 event보다 빨랐다.","실패","싼 volatility와 싼 option은 다르다."),("$23.40~27.60 within horizon","2년 내 option 2~3배가 된다.","SOTP $26~28","2007 high $23.15·year-end $16.51였다.","실패","기업 duration과 security duration을 맞춘다.")]),

I(id="87549b45-8bf7-49db-8f74-23a24e452452",date="2009-02-15",author="varna10",ticker="TWX",entity="Time Warner post-TWC content stub",group="twx",raw_short=True,direction="Stub Long",entry="stub 약 $5.04",horizon="6~18개월",filename="analysis/ideas/2009/2009-02-15_TWX_stub_long.md",link="https://www.valueinvestorsclub.com/idea/TIME_WARNER_INC/0209723699",desc=0,cat=10,title="$9.253bn cash transfer와 content stub Long",verdict="강한 성공 — TWC·AOL separation이 연속 실행",score=9.0,process=8.5,
summary="raw Short지만 실제는 TWC 분리 직전 Time Warner content stub Long이다. TWC special dividend로 약 $9.253bn cash가 들어오고, 남는 Turner/HBO·Warner Bros·AOL·Publishing을 보수적으로 합산한 약 $10/share 가치가 stub $5.04 대비 크게 높다고 봤다. recession earnings보다 이미 공시된 transaction mechanics가 edge였다.",valuation="Networks $4bn EBITDA×8x, Filmed Entertainment $1.2bn×5x, AOL $1.1bn×4x, Publishing $775m×4x에서 corporate overhead $250m×5x와 stub net debt 약 $9bn을 빼고 3.5bn shares로 나눠 약 $10를 계산했다. AOL·Publishing haircut을 줘도 announcement-to-close gap이 핵심 margin of safety였다.",actual="TWC separation은 2009년 3월 완료됐고 $9.253bn cash transfer가 이행됐다. AOL도 2009년 12월 분리됐으며 Time Inc.는 2014년에 뒤따랐다. 각 distribution·reverse split을 합친 정확 total return은 미복원이나 원문 hard catalyst는 모두 실행됐다.",price="TWC distribution, 1-for-3 reverse split, AOL distribution을 모두 연결해야 하므로 단순 TWX 차트로 수익률을 만들지 않는다. exact IRR은 null이지만 event·direction verdict는 강한 성공이다.",drivers="이미 예정된 TWC 분리와 현금유입이 balance sheet와 valuation unit을 바꾸고, AOL 분리가 두 번째 discount를 제거했다. hoped-for earnings recovery보다 legal mechanics가 직접 수익경로를 만들었다.",error="분리주식을 공짜 가치처럼 보거나 AOL·Publishing multiple과 $100m cost-cut sensitivity를 과신할 위험이 있었다. 정확한 결과는 distributed securities와 parent price를 합쳐야 한다.",first_signal="TWC special dividend가 감액되거나 tax/legal separation date가 밀리고 AOL strategic review가 중단되면 $10 stub thesis를 낮춰야 했다.",
metrics=[("Stub price/SOTP","$5.04","약 $10","separations 실행","성공"),("TWC cash transfer","$9.253bn","stub de-risk","2009-03 이행","성공"),("Networks EBITDA","$4bn×8x","가치 핵심","content company 잔존","성공"),("AOL","$1.1bn×4x","전략행위","2009-12 spin","성공"),("Total return","분리 전 common","분배증권 합산","미복원","null")],timeline=[("2009-02-15","VIC stub Long","$5.04"),("2009-03-12","TWC separation 완료","hard catalyst"),("2009-03-27","1-for-3 reverse split","price 조정"),("2009-12-09","AOL spin","두 번째 unlock"),("2014-06-06","Time Inc. spin","pure content"),("2016-10","AT&T merger agreement","strategic value"),("2018-06","AT&T close","terminal event")],
claimdata=[("TWC hard catalyst","separation은 사실상 확정됐다.","공개된 legal transaction","2009-03 완료됐다.","성공","announced event와 hoped event를 나눈다."),("$9.253bn cash","special dividend가 stub capital allocation을 바꾼다.","TWC financing·separation terms","현금이 Time Warner에 이전됐다.","성공","gross cash와 debt use를 연결한다."),("AOL strategic action","AOL을 팔거나 분리할 수 있다.","access decline·strategic review","2009-12 spin했다.","성공","challenged asset은 제거 가능성을 본다."),("cost cut·buyback","$100m/$1bn 단위로 주당가치를 높인다.","대규모 cash·overhead","방향은 맞았지만 exact sensitivity는 미검증이다.","성공 방향","capital return은 net share count로 검증한다."),("$10 SOTP","multiple expansion 없이도 stub은 두 배 가치다.","segment EBITDA·보수적 multiples","후속 분리가 가치발견을 촉진했다.","성공 방향","SOTP에 debt·tax·overhead를 넣는다."),("pure-content simplification","문제자산을 떼어 quality를 높인다.","TWC·AOL·Publishing option","세 자산이 순차 분리됐다.","강한 성공","discount보다 separation feasibility가 중요하다.")]),

I(id="07fffa81-725d-4091-9244-200083076a49",date="2013-07-24",author="Aggie1111",ticker="TWX",entity="Time Warner, Inc.",group="twx",raw_short=True,direction="Long",entry="$62.50",horizon="4년",filename="analysis/ideas/2013/2013-07-24_TWX_long.md",link="https://www.valueinvestorsclub.com/idea/TIME_WARNER_INC/0377893031",desc=14946,cat=36,title="OTT content scarcity·buyback compounding Long",verdict="성공 — 산업통찰·전략가치 적중, EPS magnitude는 과대",score=8.5,process=8.5,
summary="raw Short지만 실제 common Long이다. OTT가 cable bundle을 약화시키는 동시에 Netflix·Amazon 등 premium-content buyer를 늘려 Turner·HBO·Warner Bros. bargaining power를 높인다고 봤다. Time Inc. spin, DTC, operating leverage와 buyback으로 EPS를 high-teens 성장시켜 2017E $7.59, base $137.6 total value를 제시했다.",valuation="2017E EPS $7.59에 15x/17.5x/20x를 적용해 $114/$133/$151, 누적배당 $4.60을 더해 4년 total return 88.8%/120%/149%, base CAGR 21.8%를 계산했다. revenue growth·margin·share count와 multiple expansion을 동시에 요구하며 forecast stacking이 크다.",actual="Time Inc.는 2014년 분리됐고 HBO NOW가 2015년 출시됐다. 2016 adjusted EPS $5.86으로 강한 성장은 확인됐지만 $7.59 trajectory에는 못 미쳤다. 2014 Fox proposal과 2016 AT&T $107.50 merger agreement는 premium content의 strategic scarcity를 확인했다.",price="$62.50 대비 $107.50 headline merger value는 약 +72%이지만 배당·closing consideration·보유기간을 합친 exact IRR은 null이다. 방향과 주요 value drivers는 성공, 원문의 4년 base 120%는 미달 가능성이 높다.",drivers="Time Inc. 제거, affiliate fee·HBO growth, buyback과 strategic bid가 가치를 만들었다. OTT는 distributor와 linear filler에는 압력이지만 scarce IP owner에는 신규 수요가 될 수 있다는 가치사슬 구분이 핵심이었다.",error="2017 EPS $7.59와 17.5x를 함께 적용해 operating growth와 multiple expansion을 중첩했다. HBO를 Netflix subscriber value에 가깝게 비교할 때 성장률·content reinvestment·DTC CAC 차이를 충분히 조정하지 않았다.",first_signal="2015 EPS $4.58에서 2017 $7.59로 가려면 급격한 acceleration이 필요했다. EPS revision이 경로 아래로 내려가면 multiple 17.5x/20x 시나리오를 먼저 제거해야 했다.",
metrics=[("Entry/base value","$62.50","$137.6 incl. dividends","$107.50 merger headline","성공/target 미달"),("2017E EPS","$7.59","high-teens growth","2016 adjusted $5.86","부분 실패"),("Time Inc.","spin 예정","pure content","2014-06 완료","성공"),("HBO DTC","optional","global monetization","2015 HBO NOW","성공"),("Strategic scarcity","정성 upside","buyer premium","Fox·AT&T bids","강한 성공")],timeline=[("2013-07-24","VIC Long $62.50","4년 thesis"),("2014-06-06","Time Inc. spin","simplification"),("2014","Fox 약 $85 proposal","strategic value"),("2015-04","HBO NOW launch","DTC"),("2015","EPS $4.58","성장/forecast gap"),("2016","adjusted EPS $5.86","강한 실행"),("2016-10-22","AT&T $107.50 deal","value crystallization"),("2018-06-14","merger close","terminal")],
claimdata=[("OTT→content scarcity","신규 distribution이 premium content 수요를 늘린다.","Netflix·Amazon의 content bidding","premium IP의 strategic value가 커졌다.","성공","disruption을 가치사슬별로 나눈다."),("HBO DTC","HBO Go/standalone이 글로벌 subscriber를 연다.","brand·library·broadband 확산","HBO NOW가 2015 출시됐다.","성공","DTC는 CAC·cannibalization을 함께 본다."),("Time Inc. spin","출판을 분리해 quality multiple을 높인다.","pure-content 전략","2014년 완료됐다.","성공","portfolio simplification은 value unit을 바꾼다."),("buyback compounding","FCF buyback이 EPS를 high-teens 키운다.","3년간 $8.4bn repurchase·float -18.3%","EPS는 성장했지만 forecast보다 낮았다.","부분 성공","operating growth와 share count를 분리한다."),("2017 EPS $7.59","revenue·margin·buyback이 목표를 만든다.","5% revenue→15% EPS management sensitivity","2016 $5.86으로 gap이 남았다.","부분 실패","forecast stacking을 줄인다."),("strategic value floor","scarce IP가 buyer premium을 만든다.","Fox interest·콘텐츠 수요","AT&T가 $107.50 deal을 제시했다.","강한 성공","bid를 base와 별도 확률로 둔다.")]),

I(id="171d98eb-0b29-4b07-9074-359033065903",date="2015-01-28",author="WinBrun",ticker="TWX",entity="Time Warner, Inc.",group="twx",raw_short=True,direction="SOTP Long",entry="EV 약 $83bn",horizon="12~24개월",filename="analysis/ideas/2015/2015-01-28_TWX_sotp_long.md",link=None,desc=6904,cat=107,title="HBO+Turner가 EV를 덮는 residual WB SOTP Long",verdict="성공 — hidden asset·strategic scarcity 적중, HBO multiple은 공격적",score=8.0,process=8.0,
summary="raw Short지만 실제 SOTP Long이다. HBO 2015E EBITDA 최소 $2.3bn×15x=$34.5bn, Turner $4.4bn×10x=$44bn으로 합계 $78.5bn을 만들면 전체 EV 약 $83bn에서 Warner Bros.가 거의 공짜라는 residual-value 논리였다. HBO NOW와 후속 strategic buyer가 value-discovery route였다.",valuation="원문 SOTP는 HBO $34.5bn+Turner $44bn=$78.5bn에서 EV $83bn을 대부분 설명한다. 보수적으로 HBO 10~12x, Turner 8~9x로 낮추고 corporate overhead, net debt, tax leakage, shared rights를 모두 넣은 뒤 Warner Bros. implied value가 여전히 낮은지 확인해야 한다.",actual="HBO NOW는 2015년 출시됐고 2015 segment operating income은 Turner $4.087bn, HBO $1.878bn, Warner Bros. $1.416bn이었다. 2016 AT&T가 $107.50/share 거래를 발표하며 전체 IP portfolio에 control premium을 지급했다. hidden asset 논지는 맞았지만 Netflix식 comp transfer는 과감했다.",price="정확한 entry stock price와 dividend-adjusted IRR은 원 DB에 없어 null이다. AT&T strategic bid와 closing은 SOTP 방향을 검증하지만 투자자의 실제 보유수익과 동일하지 않다.",drivers="자산별 경제성을 분리하고 전체 EV에서 residual WB 가치를 역산한 것이 edge였다. HBO DTC와 strategic bid가 value discovery를 만들었고, public comp multiple이 비싸면 SOTP도 함께 부풀 수 있다는 위험은 남았다.",error="Netflix 고성장 multiple을 mature HBO에 가까이 적용하고 Turner의 cord-cutting duration을 낙관했다. corporate cost·debt·tax와 segment 간 권리관계를 더 엄격히 차감해야 했다.",first_signal="HBO NOW subscriber economics가 약하거나 Turner affiliate growth가 둔화하면 HBO 15x·Turner 10x를 동시에 낮추고 residual WB가 실제로 공짜인지 재검증해야 했다.",
metrics=[("Enterprise value","~$83bn","SOTP discount 해소","AT&T bid","성공"),("HBO","$2.3bn EBITDA×15x","$34.5bn","2015 OI $1.878bn","multiple 공격적"),("Turner","$4.4bn×10x","$44bn","2015 OI $4.087bn","대체로 성공"),("Warner Bros.","낮은 implied value","hidden value","2015 OI $1.416bn·buyer premium","성공"),("Value discovery","HBO NOW/bid","rerating","2015 launch·2016 deal","성공")],timeline=[("2014","Fox 약 $85 proposal","in-play evidence"),("2015-01-28","VIC SOTP Long","residual WB"),("2015-04","HBO NOW launch","DTC catalyst"),("2015 FY","segment actuals","SOTP 검증"),("2016-10","AT&T $107.50 agreement","strategic premium"),("2017-11","DOJ lawsuit","duration"),("2018-06","deal close","terminal")],
claimdata=[("HBO 15x","subscription·DTC quality는 high multiple을 받는다.","$2.3bn EBITDA·Netflix comp","strategic value는 컸지만 comp는 공격적이었다.","부분 성공","growth·reinvestment 차이를 조정한다."),("Turner 10x","affiliate fee와 brand가 value를 지지한다.","$4.4bn consensus EBITDA","당시 현금력은 확인됐고 장기 압력은 커졌다.","기간 성공","cash-flow duration을 explicit하게 둔다."),("WB residual value","HBO+Turner만으로 EV 대부분을 덮는다.","$78.5bn vs EV $83bn","AT&T가 전체 portfolio에 premium을 지급했다.","성공","SOTP는 residual implied value가 핵심이다."),("HBO NOW catalyst","standalone product가 hidden value를 드러낸다.","2015 launch 예정","월 $14.99 서비스가 출시됐다.","성공","product event와 earnings contribution을 나눈다."),("strategic optionality","Fox 철회 뒤에도 다른 buyer가 올 수 있다.","prior $85 proposal","AT&T가 $107.50 agreement를 맺었다.","강한 성공","control premium을 확률가중한다."),("SOTP convergence","시장가가 parts에 접근한다.","WB가 거의 공짜인 역산","strategic deal로 방향이 실현됐다.","성공","value-discovery route 없는 SOTP를 경계한다.")]),

I(id="92817617-f252-4c1a-9efc-0ba51eadfb06",date="2015-03-11",author="cnm3d",ticker="TWX",entity="Time Warner, Inc.",group="twx",raw_short=True,direction="Long",entry="$83",horizon="12개월",filename="analysis/ideas/2015/2015-03-11_TWX_long.md",link="https://www.valueinvestorsclub.com/idea/TIME_WARNER_INC/2136029077",desc=0,cat=86,title="$6 EPS·buyback·strategic optionality Long",verdict="부분 성공 — earnings power 적중, 12개월 $110은 지연",score=7.5,process=8.5,
summary="raw Short지만 실제 common Long이다. $83에서 2015 EBITDA +8%, 2016 +12%, 매년 $3~4bn buyback으로 2016 EPS 약 $6을 만들고 18x를 적용해 12개월 $110을 제시했다. downside는 $5.25×14=$74, execution이 약해도 strategic buyer가 등장할 수 있다는 두 번째 경로였다.",valuation="Base는 2016 EPS $6×18x≈$108을 반올림한 $110이다. Downside는 EBITDA +5%, EPS $5.25×14x=$73.5다. SOTP로 HBO $35bn, WB $20bn, Turner $50bn, EV $105bn도 제시했다. EPS growth·buyback·multiple과 M&A option의 상관을 낮게 본 위험이 있다.",actual="2016 adjusted EPS는 $5.86으로 $6 earnings-power 가정에 근접했다. 다만 12개월 $110 달성 근거는 확인하지 못했고 19개월 뒤인 2016-10 AT&T가 $107.50 merger agreement를 발표했다. 사업·전략가치는 맞았지만 horizon은 짧았다.",price="12개월 exact price series가 없어 target 달성은 미검증/지연으로 둔다. 2016 deal headline $107.50는 $110보다 낮고 12개월을 넘었다. 배당과 2018 closing까지의 total return은 null이다.",drivers="affiliate fee, HBO monetization, FCF buyback이 EPS를 키웠고 strategic buyer가 terminal value를 확인했다. 그러나 event option은 fundamental rerating을 대신할 수 없었고 DOJ 소송은 value crystallization을 더 늦췄다.",error="'실적이 좋으면 18x, 약하면 buyer가 산다'는 two-way win의 상관을 과소평가했다. buyer도 약한 실적에는 낮은 multiple을 지불할 수 있고 regulatory duration도 무시됐다.",first_signal="2015 quarterly EPS revision과 buyback pace가 $6 trajectory를 못 따라가거나 12개월 내 multiple이 움직이지 않으면 $110 target을 폐기하고 strategic option을 별도 확률로 낮춰야 했다.",
metrics=[("Entry/target","$83/$110","12개월 +33%","$107.50 deal at 19개월","horizon 실패"),("2016 EPS","약 $6","18x","$5.86 adjusted","성공"),("Downside","$5.25×14=$74","방어","미복원","미검증"),("Buyback","$3~4bn/yr","EPS 증폭","지속 방향","성공"),("Strategic bid","optional","second way to win","AT&T agreement","강한 성공")],timeline=[("2015-03-09","HBO NOW 발표","DTC"),("2015-03-11","VIC Long $83","12M clock"),("2015 FY","EPS $4.58","중간 checkpoint"),("2016 FY","adjusted EPS $5.86","$6 접근"),("2016-10-22","AT&T $107.50 agreement","19개월"),("2017-11","DOJ lawsuit","delay"),("2018-06-14","deal close","terminal")],
claimdata=[("affiliate fee growth","Turner 계약 reset이 low-teens 성장한다.","revenue 약 20%의 계약 reset","near-term earnings를 지지했다.","성공","contracted growth와 churn을 같이 본다."),("HBO monetization","international·ARPU가 under-earned다.","premium brand·DTC launch","DTC/strategic value가 커졌다.","성공 방향","subscriber보다 contribution을 본다."),("HBO NOW optionality","base EPS가 아닌 10~15¢ upside다.","launch economics sensitivity","headline을 base와 분리한 process는 좋았다.","성공","옵션을 base forecast와 분리한다."),("$3~4bn buyback","FCF repurchase가 EPS $6을 만든다.","leverage capacity·share count","2016 EPS $5.86으로 근접했다.","성공","buyback은 가격과 순주식수로 본다."),("12M $110","$6×18x로 빠르게 rerate한다.","business momentum·SOTP","기간 안 달성 근거가 없다.","실패/지연","target에는 calendar가 필요하다."),("strategic buyer","execution failure에도 희소자산 buyer가 있다.","Fox precedent","AT&T가 2016 bid했다.","강한 성공","M&A는 probability-weighted option이다.")]),

I(id="91c79f18-515f-4cbe-a4c3-cdf5d379c922",date="2015-12-10",author="alex981",ticker="TWX",entity="Time Warner, Inc.",group="twx",raw_short=True,direction="Short",entry="market cap $55bn / EV $76bn",horizon="2~10년",filename="analysis/ideas/2015/2015-12-10_TWX_short.md",link=None,desc=29270,cat=30,title="linear cable terminal decline Short",verdict="강한 실패 — 산업방향 일부 적중, M&A tail이 security를 파괴",score=3.5,process=7.0,
summary="raw와 실제 방향이 모두 Short다. Turner 중심 cable-network profit이 broadband·Netflix·OTT 침투로 terminal decline에 들어가는데 시장은 LTM EBITDA 약 $7.8bn의 10x를 준다고 봤다. less-challenged WB/CNN과 runoff cash flow를 합쳐 equity를 $17.50, 많아도 $20로 평가했다.",valuation="WB+CNN operating income 약 $2bn×10x=$20bn, 나머지 cable networks 약 $5bn OI가 5년 유지된 뒤 2021부터 zero로 내려가는 DCF 약 $15bn을 합치고 net debt $21bn을 차감해 equity $17.50를 계산했다. 핵심 민감도는 decline 속도뿐 아니라 cash harvest duration과 strategic control premium이다.",actual="cord-cutting·streaming shift와 sports-rights inflation은 장기적으로 현실화됐다. 그러나 2016 adjusted EPS가 $5.86으로 전년 대비 강하게 늘었고, 게시 10개월 뒤 AT&T가 $107.50 거래를 발표했다. DOJ 소송 뒤에도 거래는 2018년 완료되어 common Short의 terminal 결과는 강한 실패다.",price="정확한 entry·borrow·cover·배당 비용은 없어 short IRR은 null이다. 다만 2016 $107.50 bid와 2018 closing은 security-level 실패를 명확히 한다. 장기 산업논지가 맞았다는 사실은 당시 short 손익을 구제하지 못한다.",drivers="손실을 만든 직접 원인은 near-term earnings resilience와 rare content/IP의 buyer optionality였다. linear distribution decline은 느렸고 Turner·HBO·WB의 control value는 public runoff multiple보다 높았다.",error="원문이 Fox의 재인수 가능성을 risk로 적었지만 payoff tree와 sizing에 넣지 않았다. declining distribution layer와 scarce content layer를 한 기업 multiple로 묶고 earnings revision timing을 과도하게 앞당겼다.",first_signal="T0부터 prior Fox proposal이 있었다. 더 직접적으로 2016 adjusted EPS +23%가 near-term runoff를 반증했을 때 short를 줄여야 했고, deal rumor 이전에도 M&A probability를 올려야 했다.",
metrics=[("EV/LTM EBITDA","$76bn/$7.8bn≈9.7x","<5x runoff","$107.50 bid","실패"),("Fair equity","$17.50~20","대폭 하락","strategic premium","대실패"),("2016 EPS","decline 예상","estimate cuts","$5.86·+23%","반증"),("Linear cable","terminal decline","빠른 이익훼손","장기 pressure·단기 resilient","timing 실패"),("M&A tail","risk로만 언급","낮은 확률","AT&T deal close","치명적 실패")],timeline=[("2014","Fox proposal·철회","known M&A tail"),("2015-12-10","VIC Short","runoff thesis"),("2016 FY","adjusted EPS $5.86","near-term 반증"),("2016-10-22","AT&T $107.50 agreement","short shock"),("2017-11-20","DOJ suit","spread volatility"),("2018-06-12","법원 DOJ challenge 기각","closing gate"),("2018-06-14","acquisition 완료","terminal failure")],
claimdata=[("linear scripted decline","OTT가 linear cable viewing을 구조적으로 빼앗는다.","Netflix growth·broadband penetration","장기 방향은 현실화됐다.","장기 성공","terminal thesis와 trade horizon을 나눈다."),("sports-rights pressure","premium sports cost가 Turner margin을 압박한다.","rights inflation·live value","산업 핵심 리스크가 됐다.","성공 방향","비용 상승과 affiliate repricing을 같이 본다."),("HBO structural weakness","Netflix scale/content spend가 HBO를 압도한다.","DTC economics 비교","HBO brand·IP가 strategic value를 유지했다.","부분 실패","콘텐츠 질·ARPU·CAC를 맞춘다."),("runoff 3~5x","non-WB/CNN assets는 짧은 cash duration이다.","subscriber decline DCF","현금흐름 duration을 너무 짧게 봤다.","실패","decline rate와 cash harvest를 분리한다."),("debt+buyback","$21bn debt와 고평가 buyback이 equity를 파괴한다.","capital allocation·leverage","buyer가 먼저 control premium을 지급했다.","단기 실패","credit risk와 M&A를 함께 둔다."),("no strategic rescue","M&A risk는 있어도 base가 아니다.","Fox 가능성을 risk에 명시","AT&T 거래가 실제로 닫혔다.","치명적 실패","known tail을 sizing 중심에 둔다.")]),

I(id="a32500d7-d85f-41a7-a66b-cba1ec17747e",date="2017-02-22",author="rhianik",ticker="TWX",entity="Time Warner / AT&T merger claim",group="twx",raw_short=True,direction="Merger Arb Long",entry="implied consideration 약 $107.80",horizon="2017-12-31 close 가정",filename="analysis/ideas/2017/2017-02-22_TWX_merger_long.md",link="https://www.valueinvestorsclub.com/idea/TIME_WARNER_INC/2622171445",desc=0,cat=84,title="AT&T cash-stock collar merger-arbitrage Long",verdict="성공 — deal close, regulatory simplicity·duration은 실패",score=8.0,process=8.0,
summary="raw Short지만 실제는 AT&T/Time Warner merger-arbitrage Long이다. $53.75 cash와 AT&T stock collar를 합친 당시 implied consideration 약 $107.80 대비 absolute spread 약 12%, year-end 2017 close 가정 annualized 약 14%와 TWX 배당 1.8%를 기대했다. vertical deal·FCC license 이슈 제한으로 closing probability가 높다고 봤다.",valuation="stock leg는 T 15-day VWAP가 $37.411 아래면 1.437주, $41.349 위면 1.3주, 중간이면 $53.75/VWAP다. expected IRR은 `확률가중 consideration/entry-1`을 expected duration으로 연율화하고 T short dividend·borrow·financing cost와 break loss를 차감해야 한다. 2017-12-31이라는 단일 날짜가 가장 큰 sensitivity였다.",actual="DOJ는 2017-11-20 거래 저지 소송을 제기했고 법원 판단을 거쳐 2018-06-14에야 closing했다. 최종 TWX 1주당 $53.75 cash+1.437 AT&T shares가 지급됐다. deal direction은 맞았지만 routine vertical review라는 규제경로와 duration 가정은 틀렸다.",price="hedge ratio, T short entry·배당, TWX 배당, financing cost가 없어 exact arb IRR은 null이다. absolute deal leg는 성공했으나 closing이 약 5.5개월 늦어져 annualized return은 원문 14%보다 낮아졌다.",drivers="spread 수렴은 법원 승소와 closing이 만들었다. 반대로 DOJ litigation은 duration·mark-to-market·financing cost를 늘렸다. probability와 duration을 독립 변수가 아니라 litigated path의 결합분포로 봐야 했다.",error="정치발언은 할인하면서 실제 DOJ 소송 branch를 거의 두지 않았다. vertical precedent만으로 regulatory simplicity를 결론내리고 stock collar와 long/short dividend carry의 경로를 충분히 모델링하지 않았다.",first_signal="2017-11-20 DOJ complaint가 제출된 순간 routine arb가 litigated arb로 바뀌었다. position size·break price·6/12개월 delay IRR을 완전히 다시 계산해야 했다.",
metrics=[("Implied consideration","~$107.80","12% absolute","$53.75+1.437 T shares","성공"),("Annualized spread","~14%","2017-12-31 close","2018-06-14 close","하향"),("TWX dividends","3~4×$0.405","~1.8% 보완","closing 전 지급","성공"),("Regulatory path","vertical/simple","소송 없음","DOJ litigation","실패"),("Break downside","peer-like valuation","제한적","deal closed","미검증")],timeline=[("2016-10-22","merger agreement","cash-stock collar"),("2017-02-15","shareholder approval","closing gate"),("2017-02-22","VIC arb Long","14% annualized"),("2017-11-20","DOJ lawsuit","litigated arb"),("2018-03~06","antitrust trial","duration"),("2018-06-12","법원 challenge 기각","close 가능"),("2018-06-14","acquisition 완료","deal success")],
claimdata=[("high close probability","vertical integration이라 거래가 닫힌다.","shareholder approval·asset quality","최종 close했다.","성공","probability와 path를 분리한다."),("regulatory simplicity","FCC transfer·horizontal overlap가 제한적이다.","vertical-deal precedent","DOJ가 실제 소송을 제기했다.","실패","기관 jurisdiction보다 remedy theory를 본다."),("year-end 2017 close","review가 10개월 안에 끝난다.","회사 guidance·거래구조","2018-06까지 지연됐다.","실패","3/6/12개월 delay IRR을 만든다."),("limited break downside","fail해도 TWX standalone valuation은 견고하다.","premium content·peer multiple","deal이 닫혀 관찰되지 않았다.","미검증","unaffected price와 peer beta를 stress한다."),("collar hedge","AT&T stock leg를 비율대로 hedge할 수 있다.","1.3~1.437 share collar","최종 1.437주가 지급됐다.","성공","VWAP window에 맞춰 delta를 조정한다."),("dividend carry","TWX 배당이 기다림을 보완한다.","분기 $0.405 예상","배당은 받았지만 T short carry도 있었다.","부분 성공","양쪽 배당·borrow를 netting한다.")]),

I(id="5faa64ca-3af9-41b2-bfe0-b7377094617b",date="2003-10-13",author="zach721",ticker="MUSA",entity="Metals USA, Inc. (not Murphy USA)",group="metalsusa",raw_short=False,direction="Long",entry="원문 upside 역산 약 $7.10",horizon="12~36개월",filename="analysis/ideas/2003/2003-10-13_MUSA_metalsusa_long.md",link="https://www.valueinvestorsclub.com/idea/Metals_USA/0073403264",desc=0,cat=362,title="post-bankruptcy 자산·운전자본·operator reset Long",verdict="강한 성공 — 2005 Apollo $22 cash exit, 약 3.1x gross",score=9.5,process=8.5,
summary="raw와 실제 모두 Long이며 MUSA는 Murphy USA가 아니라 Metals USA다. 53개 acquisition roll-up이 debt·통합실패로 Chapter 11을 거친 뒤 unsecured debt 약 $365m을 equity로 바꾸고, 새 CEO Lourenco Goncalves가 inventory·안전·ERP·구매를 정상화했다. NNWC $8.99/share, working capital $13.32, adjusted book $14.36과 normalized FCF $2.17/share가 entry 약 $7.10을 방어했다.",valuation="Asset floor는 NNWC $8.99, WC $13.32, hidden PP&E를 더한 adjusted book 약 $14.36이다. Peer comp 약 $15.02, normalized FCF $2.17×8~10x=$17.42~21.17을 제시했다. 원문 $11.70=+65%, $15.02=+112%에서 entry를 약 $7.1로 역산한다. WC release·PP&E·earning power의 double counting을 막아야 한다.",actual="Chapter 11 emergence와 CEO 교체 뒤 inventory·운전자본·수익성이 개선됐고 steel/service-center cycle도 회복됐다. Apollo affiliate는 2005-11-30 Metals USA를 $22 cash/share에 인수 완료했다. 역산 entry 대비 약 3.1x gross outcome으로 원문 상단 valuation도 넘어섰다.",price="약 $7.10 entry는 직접 quote가 아니라 원문 upside percentage의 역산값이다. $22 cash exit와 비교하면 약 +210%, 3.1x gross지만 정확 게시일 close·dividend·tax를 복원하지 않아 공식 IRR은 null이다.",drivers="capital structure reset이 operating improvement를 common에 전달했고, 새 CEO가 inventory turns·procurement·safety·systems를 바꿨다. working-capital release와 steel cycle 회복이 FCF를 높였고 buyer가 개선된 franchise에 cash premium을 지급했다.",error="NNWC, hidden PP&E, WC release와 normalized earnings를 동시에 더하면 margin of safety를 중복 계산할 수 있다. inventory price 상승이 CFO를 좋아 보이게 하면서 reversal risk를 키우는 점도 더 stress해야 했다.",first_signal="inventory turns가 개선되지 않고 working capital/revenue가 30% 부근에 머물거나 normalized EBITDA margin이 5% 아래면 operator thesis를 낮춰야 했다.",
metrics=[("Entry/exit","~$7.10","$12~21","$22 cash","강한 성공"),("NNWC/share","$8.99","asset floor","buyer premium","성공"),("Working capital","30% of revenue","24%·$2.66/share release","운영개선 방향","성공"),("Normalized FCF","$2.17/share","8~10x","$22 transaction","성공"),("Balance sheet","$365m debt→equity","deleveraged","post-BK convexity","성공")],timeline=[("2002-11","Chapter 11 emergence","balance-sheet reset"),("2003-02","Lourenco Goncalves CEO","operator reset"),("2003-10-13","VIC Long","~$7.10"),("2004~05","cycle·실적 회복","earning power"),("2005-05-18","Apollo agreement","$22 cash"),("2005-11-30","acquisition close","3.1x gross")],
claimdata=[("balance-sheet reset","bankruptcy가 roll-up debt를 equity로 바꿨다.","$365m unsecured debt·52.5¢ exchange","operating upside가 common에 귀속됐다.","성공","post-BK는 새 waterfall부터 본다."),("WC normalization","30% revenue의 WC가 24%로 내려간다.","peer 20%·inventory reduction","현금창출과 buyer value를 지지했다.","성공 방향","release와 recurring FCF를 나눈다."),("operator change","새 CEO가 safety·ERP·procurement를 고친다.","California Steel turnaround record","실행 개선 뒤 cash takeout이 왔다.","강한 성공","인물보다 measurable levers를 본다."),("hidden PP&E","fresh-start carrying value가 economic value보다 낮다.","약 $105m economic vs $6m carrying 추정","asset backing을 강화했다.","성공 방향","going concern과 liquidation을 중복하지 않는다."),("normalized margin/FCF","6~7% margin·낮은 capex가 $2.17 FCF/share를 만든다.","$12~14m maintenance capex·scale","$22 buyer price가 상단을 확인했다.","성공","cycle peak가 아닌 full-cycle margin을 쓴다."),("$12~21 valuation","asset·peer·FCF 세 축이 큰 upside를 준다.","$8.99 NNWC·$15.02 comp·$17~21 FCF","$22 cash exit가 실현됐다.","강한 성공","서로 독립적인 valuation만 교차검증한다.")])
]

def patch_performance(payload):
    by_id = {row["idea_id"]: row for row in payload["ideas_master"]}
    pm = {row["idea_id"]: row for row in payload["postmortems"]}
    for iid, values in PERF.items():
        row = by_id[iid]
        row["performance_available"] = 1
        for key in ("1m", "3m", "6m", "1y", "2y", "3y", "5y"):
            row[f"perf_{key}"] = values.get(key)
        row["idea_return_1y"] = values.get("1y") - 1 if values.get("1y") is not None else None
        row["idea_return_3y"] = values.get("3y") - 1 if values.get("3y") is not None else None
        row["idea_return_5y"] = values.get("5y") - 1 if values.get("5y") is not None else None
        pm[iid]["corrected_return_1y"] = row["idea_return_1y"]
        pm[iid]["corrected_return_3y"] = row["idea_return_3y"]
        pm[iid]["corrected_return_5y"] = row["idea_return_5y"]
        pm[iid]["confidence"] = 0.97
        pm[iid]["research_status_ko"] = "SQL 원문·공식 사건 검증 완료; repository price multiplier를 실제 Long 방향으로 교정"
    return payload

def make_index(ideas):
    rows = []
    for n, idea in enumerate(ideas, 1):
        raw = "Short" if idea["raw_short"] else "Long"
        rel = Path(idea["filename"]).relative_to("analysis")
        rows.append(f"| {n} | {idea['date']} | {idea['entity']} | {raw}→**{idea['direction']}** | {idea['verdict']} | [{idea['title']}]({rel}) |")
    return "\n".join([
        "# Batch 048 — KAR / Time Warner / Metals USA — V9 Index", "",
        f"> Research as-of {ASOF}. 첨부 `VIC_IDEAS(4).sql`과 repository source metadata로 entity·direction·security를 감사했다. KAR 2건은 보존 price multiplier를 실제 Long 방향으로 교정했고, 나머지는 성과를 만들지 않았다.", "",
        "## 0. 배치 결론", "",
        "raw Short 9건 중 실제 Short는 TWX 2015-12 한 건뿐이다. KAR 2건은 recovery/digital Long, TWX는 LEAPS·stub·common·SOTP·Short·merger arb를 각각 독립 security로 나눴다. MUSA 2003은 Murphy USA가 아니라 Metals USA다. 이 배치의 핵심은 `좋은 기업가치 분석도 security duration이 틀리면 실패`, `산업 Short가 맞아도 M&A tail이면 손실`, `event probability와 duration은 별도`라는 점이다.", "",
        "## 1. Idea Units", "", "| # | 날짜 | 실제 security/entity | raw→연구 방향 | 판정 | Canonical report |", "|---:|---|---|---|---|---|", *rows, "",
        "## 2. 기업별 lifecycle", "",
        "### KAR — survival에서 digital perimeter로", "", "2020 Long은 $550m preferred로 생존확률이 상승하는 trade였고 1년 +16.4%로 부분 성공했다. 2021 Long은 BacklotCars·commercial workflow를 맞게 봤지만 2022 ADESA U.S. 매각으로 2024 $585m EBITDA forecast object가 소멸했다.", "",
        "### Time Warner — 같은 기업, 다른 security와 clock", "", "2006 LEAPS는 TWC/AOL 분리 방향이 맞아도 만기 전에 오지 않아 실패했다. 2009 stub은 hard separation으로 성공했다. 2013~2015 Long은 content scarcity·buyback·strategic value를 포착했다. 2015 Short는 cord-cutting을 맞히고 AT&T bid로 크게 실패했으며 2017 arb는 close probability를 맞히고 DOJ/duration을 틀렸다.", "",
        "### Metals USA — post-bankruptcy convexity", "", "debt-to-equity reset, working-capital release, operator change와 steel cycle이 겹쳤고 2005 Apollo $22 cash exit로 약 3.1x gross outcome을 만들었다.", "",
        "## 3. 공통 투자교훈", "",
        "1. **기업 thesis와 security thesis를 분리한다.** LEAPS 만기는 corporate value를 기다려주지 않는다.\n2. **산업 terminal value와 주식 경로는 다르다.** 희소 IP의 strategic buyer가 secular Short를 파괴할 수 있다.\n3. **Merger arb는 probability×duration×hedge carry다.** 결국 닫혀도 annualized IRR은 실패할 수 있다.\n4. **Forecast perimeter를 고정하지 않는다.** 핵심 자산 매각 뒤에는 옛 EBITDA/SOTP를 폐기한다.\n5. **SOTP는 residual implied value를 본다.** debt·tax·overhead를 넣은 뒤 진짜 공짜인지 확인한다.\n6. **Post-BK는 asset floor와 recurring FCF를 중복하지 않는다.**\n7. **성과가 없으면 null이다.** corporate action을 임의 return으로 바꾸지 않는다.", "",
        "## 4. 산출물", "", "- Payload: `data/curated/batch_048_kar_timewarner_metalsusa_deep_v7.json`\n- Wrapper: `analysis/batch_048_kar_timewarner_metalsusa_10.md`\n- Source packet: `data/curated/batch_048_source_packet.json`\n- Builder: `scripts/48_build_batch_048_v9.py`", ""
    ])

def main():
    assert len(IDEAS) == 10 and len({i["id"] for i in IDEAS}) == 10
    for idea in IDEAS:
        assert len(idea["claims"]) == 6 and len(idea["metrics"]) == 5 and len(idea["timeline"]) >= 6
        text = m.report(idea)
        generic_performance = "이번 10건은 첨부 SQL에 performance row가 없으므로 1개월~5년 수익률을 만들지 않는다. 사건 성공, 기업 생존, target 도달과 투자 total return을 각각 별도 필드로 둔다. corporate action이 있으면 successor security까지 연결돼야 정확한 IRR을 계산할 수 있다."
        if idea["id"] in PERF:
            text = text.replace(generic_performance, "이 아이디어는 repository에 보존된 price multiplier를 실제 Long 방향으로 교정했다. `multiplier-1`은 price-only 수익이며 배당·preferred dilution·거래비용을 포함하지 않는다. 누락 horizon은 null이다.")
        else:
            text = text.replace(generic_performance, "이 아이디어는 첨부 SQL과 repository source layer에 검증된 performance row가 없어 1개월~5년 수익률을 만들지 않는다. 사건 성공, target 달성과 투자 total return을 각각 별도 필드로 두며 누락값은 null이다.")
        text = text.replace(f"1. **Entity audit:** `ATH`를 회사로 보지 말고 {idea['entity']} 법인·exchange·날짜로 고정한다.", f"1. **Entity audit:** ticker `{idea['ticker']}`만 보지 말고 {idea['entity']}의 법인·증권·날짜로 고정한다.")
        path = ROOT / idea["filename"]
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    parts = [Path(i["filename"]).relative_to("analysis").as_posix() for i in IDEAS]
    wrapper = "# Batch 048 — KAR / Time Warner / Metals USA V9\n\n" + f"<!-- batch_parts: {'|'.join(parts)} -->\n\n" + "> Streamlit 호환 wrapper다. canonical index: [Batch 048 V9 Index](batch_048_v9_index.md).\n"
    (ROOT / "analysis/batch_048_kar_timewarner_metalsusa_10.md").write_text(wrapper, encoding="utf-8")
    (ROOT / "analysis/batch_048_v9_index.md").write_text(make_index(IDEAS), encoding="utf-8")
    payload = patch_performance(m.make_payload(IDEAS))
    payload["batch"] = 48
    payload["title"] = "KAR / Time Warner / Metals USA — Direction, Security, Duration and Event Path V9"
    payload["research_asof"] = ASOF
    (ROOT / "data/curated/batch_048_kar_timewarner_metalsusa_deep_v7.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    packet = {"batch": "048", "format": "V9-per-idea", "source": "VIC_IDEAS(4).sql + repository source metadata", "record_count": 10, "direction_audit": "complete", "direction_corrections": 8, "performance_rows_preserved": 2, "performance_rule": "KAR 2건만 보존 multiplier를 실제 Long 방향으로 교정; 나머지는 null", "candidates": [{"idea_id": i["id"], "date": i["date"], "ticker": i["ticker"], "company_name": i["entity"], "author": i["author"], "raw_direction": "Short" if i["raw_short"] else "Long", "research_direction": i["direction"], "description_chars": i["desc"], "catalyst_chars": i["cat"], "performance_available": i["id"] in PERF, "canonical_report": i["filename"]} for i in IDEAS]}
    (ROOT / "data/curated/batch_048_source_packet.json").write_text(json.dumps(packet, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    inventory = {"source_filename": "VIC_IDEAS(4).sql", "attachment_bytes_checked": 122499072, "records_selected": 10, "raw_descriptions_present_in_attachment": 5, "raw_catalysts_verified": 10, "repository_performance_rows_preserved": 2, "direction_corrections": 8, "entity_corrections": 1, "note": "첨부 SQL은 10건 catalyst와 5건 description을 포함했다. 누락 description은 길이를 0으로 유지했다. KAR 2건의 repository multiplier 외 성과는 만들지 않았다."}
    (ROOT / "data/curated/batch_048_sql_inventory.json").write_text(json.dumps(inventory, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print({k: len(payload[k]) for k in ("ideas_master", "postmortems", "sections", "claims", "metrics", "timeline", "sources")})

if __name__ == "__main__":
    main()
