#!/usr/bin/env python3
"""Build Batch 051 Genworth MI Canada / Macquarie Infrastructure / MSG V9 artifacts."""
from __future__ import annotations
import importlib.util, json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; ASOF="2026-09-10"
spec=importlib.util.spec_from_file_location("batch46",ROOT/"scripts/46_build_batch_046_v9.py")
m=importlib.util.module_from_spec(spec); spec.loader.exec_module(m); m.ASOF=ASOF

m.BUSINESS.update({
"gmic":"Genworth MI Canada(현 Sagen)는 캐나다 주택담보대출기관에 borrower-default 보험을 제공한다. 현금엔진은 `insured mortgage volume×premium rate+투자수익-발생손해-loss adjustment expense-운영비-세금-필요자본 증가`다. 보험료는 upfront, claim은 경기후퇴 뒤 늦게 나오므로 당기 ROE만 보면 tail을 놓친다. recourse·은행 underwriting, LTV·credit score·지역·vintage, cure·foreclosure severity, 정부보증과 OSFI capital이 loss ratio와 배당가능자본을 결정한다.",
"mic":"Macquarie Infrastructure는 IMTT 액체저장터미널, Atlantic Aviation FBO, Hawaii Gas·propane을 보유한 외부운용 holding company였다. 초기 현금엔진은 `자회사 EBITDA-capex-이자·세금-covenant cash trap-holdco cost·manager fee`, 2019년 이후에는 `자산별 sale EV-debt-tax-transaction·manager disposition fee-wind-down cost`다. 장기계약도 utilization·renewal·airport lease와 upstream covenant가 나쁘면 holdco dividend가 끊긴다. payout이 깨진 뒤에도 매각·분배가 확정되면 liquidation claim으로 다시 평가할 수 있다.",
"msg":"2010년 Madison Square Garden은 MSG·MSG+ RSN, Knicks·Rangers·Liberty, Garden·Radio City venue와 live entertainment를 한 증권에 담았다. 현금엔진은 `affiliate fee+광고+ticket·suite·sponsorship+venue 수익-media rights-team payroll-event cost-overhead-renovation capex`다. RSN은 subscriber·affiliate rate·rights duration, franchise는 희소성·league economics·control discount, venue는 utilization·renovation return이 핵심이다. 2015·2020 분할 뒤 모든 분배증권을 합쳐야 원 common의 total return을 계산한다."
})
m.SOURCES.update({
"gmic":[m.S("Sagen corporate overview","https://investor.sagen.ca/English/home/default.aspx","Sagen MI Canada","2026","2009~2021 TSX MIC 법인과 Brookfield 100% 보유"),m.S("OSFI Mortgage Insurance","https://www.osfi-bsif.gc.ca/en/guidance/guidance-library/mortgage-insurance","OSFI","2010-06-30","80% LTV 초과 대출의 보험요건과 lender-insurer 구조"),m.S("Genworth SEC archive","https://www.sec.gov/edgar/browse/?CIK=1276520&owner=exclude","SEC / Genworth","2009-2020","IPO·majority stake·Brookfield 거래"),m.S("Genworth sale completion","https://investor.genworth.com/news-events/press-releases","Genworth Financial","2019-12-12","C$48.86/share Brookfield 거래 종결")],
"mic":[m.S("MIC SEC archive","https://www.sec.gov/edgar/browse/?CIK=1289790&owner=exclude","SEC / MIC","2004-2021","segment FCF·covenant·distribution·asset sale"),m.S("IMTT sale / $11 dividend","https://www.sec.gov/Archives/edgar/data/1289790/000115752320001625/a52353418ex99_1.htm","SEC / MIC","2020-12-23","$2.67bn close와 $11/share"),m.S("Atlantic close / distribution","https://www.sec.gov/Archives/edgar/data/1845290/000110465921118596/tm2128286d1_ex99-1.htm","SEC / MIC LLC","2021-09-23","$4.475bn close와 $37.386817/unit"),m.S("IMTT operations","https://imtt.com/","IMTT","2026","40m barrels 북미 bulk-liquid storage")],
"msg":[m.S("MSG SEC archive","https://www.sec.gov/edgar/browse/?CIK=1469372&owner=exclude","SEC / MSG","2009-2015","segment·renovation·분할"),m.S("2015 separation close","https://www.msgsports.com/the-madison-square-garden-company-becomes-new-public-sports-and-entertainment-company/","MSG Sports","2015-10-01","구 MSG 3주당 신 MSG 1주"),m.S("2015 spin documents","https://investor.msgsports.com/information-on-the-2015-spin-off-from-msg-networks/default.aspx","MSG Sports","2015","information statement·세무"),m.S("2020 entertainment spin","https://investor.msgsports.com/press-releases/news-details/2020/Madison-Square-Garden-Sports-Corp-Completes-Spin-Off-of-Entertainment-Businesses/default.aspx","MSG Sports","2020-04-20","MSGS 1주당 MSGE 1주")]
})

def C(title,original,evidence,assumption,falsifier,actual,verdict,lesson): return m.C(title,original,evidence,assumption,falsifier,actual,verdict,lesson)
def I(**x):
 x["claims"]=[C(*z) for z in x.pop("claimdata")]; x.setdefault("security","Common equity"); x.setdefault("waterfall","영업현금에서 capex·이자·세금·manager/holdco 비용과 선순위 부채를 차감한 뒤 common에 남는 현금만 가치다."); return x

IDEAS=[
I(id="3b9202d5-f12b-4285-940b-b2ed2ae59efe",date="2009-12-29",author="xanadu972",ticker="MIC",entity="Genworth MI Canada Inc. (현 Sagen MI Canada Inc.)",group="gmic",raw_short=True,direction="Long",entry="C$24 부근",horizon="4~5년",filename="analysis/ideas/2009/2009-12-29_MIC_genworth_canada_long.md",link=None,desc=5042,cat=117,title="캐나다 mortgage-insurance 구조·20%+ 자본복리 Long",verdict="장기 강한 성공 — C$48.86 control transaction",score=9.0,process=8.1,
summary="raw Short지만 명백한 Long이며 미국 Macquarie가 아니라 TSX Genworth MI Canada다. 미국식 non-recourse 직관을 캐나다에 투영한 housing fear 속에서 recourse·은행 underwriting·시장집중, 높은 premium·낮은 loss ratio와 excess capital이 20%+ book compounding을 만들고 C$24에서 40%+ upside가 있다고 봤다.",valuation="약 15% ROE franchise에 최소 1.5x forward book을 적용했다. excess capital buyback 시 2014 EPS C$7.39, 2010 PV C$5.05와 4~5% dividend를 제시했다. 안전한 bridge는 `opening book+retained earnings-stress loss-capital return`이며 MICAT buffer를 매년 갱신한다.",actual="book·dividend는 성장했다. 2019 Genworth는 48,944,645주 약 57%를 Brookfield에 C$48.86/share, 약 C$2.4bn에 매각했고 이후 Sagen으로 개명해 2021 common이 비상장화됐다.",price="C$24는 원문 제안가, C$48.86은 2019 control 거래가다. 배당·배분시점·체결가가 없어 exact return/IRR은 null이다.",drivers="recourse와 은행 underwriting, upfront premium·float·시장집중이 높은 ROE를 만들고 retained earnings·capital return·strategic buyer가 가치를 실현했다.",error="C$7.39 EPS는 buyback·높은 ROE·낮은 loss의 동시지속이 필요했다. unemployment·regional HPI·90+ day delinquency별 stress loss가 부족했다.",first_signal="loss ratio가 두 분기 정상범위를 넘고 신규보험·capital return이 줄거나 MICAT buffer가 급락하면 1.5x book을 폐기한다.",metrics=[("Entry/transaction","C$24","+40%","C$48.86 control","성공"),("ROE","약 15%+","20%+ book compound","franchise ROE 지속","성공"),("P/B","discount","≥1.5x forward","control value","성공"),("2014 EPS","C$7.39 case","C$5.05 PV","미복원","미검증"),("Capital return","4~5%+buyback","excess 환원","배당·거래","성공")],timeline=[("2009-07","IPO","TSX MIC"),("2009-12-29","VIC Long","C$24"),("2010","OSFI 규정","구조 확인"),("2010s","book·dividend 성장","복리"),("2019-08-13","Brookfield 발표","C$48.86"),("2019-12","57% close","control"),("2020","Sagen 개명","연속성"),("2021-04","100% 보유","terminal")],claimdata=[("캐나다 계약구조","recourse·은행심사가 미국식 손실을 막는다.","lender가 insurer 선택·high-ratio 심사","incentive가 stress에도 작동","vintage severity 급등 시 반증","loss economics 견고","성공","국가가 아니라 계약·claim waterfall을 비교한다."),("시장집중·pricing","집중시장이 높은 ROE를 지킨다.","진입규제·lender integration","가격경쟁 제한","rate·share 동시하락 시 반증","largest private insurer 유지","성공","price·share·capital로 검증한다."),("20%+ book 복리","보험이익·float가 book/share를 키운다.","높은 ROE·낮은 payout","loss·capital 안정","2년 CAGR<15%면 반증","장기 가치 상승","성공","vintage loss와 capital로 bridge한다."),("excess-capital buyback","할인매입이 EPS C$7.39를 만든다.","초과자본·낮은 P/B","stress 후 여력","MICAT·배당제한 시 반증","환원은 실행·exact EPS 미검증","부분","stress 뒤 잔여자본만 쓴다."),("1.5x book","15% ROE는 최소 1.5x book이다.","peer·지속 ROE","cost of equity 안정","ROE<12%면 반증","C$48.86 거래","성공","P/B를 ROE·g·r로 해체한다."),("housing 안정","macro 개선이 claim tail을 낮춘다.","2009 stabilization","regional shock 없음","arrears 재악화 시 반증","systemic loss 없이 회복","성공","delinquency→claim→severity로 잇는다.")]),

I(id="78c6b9bb-714a-464d-a010-cd87877fcd6d",date="2010-06-03",author="jazz678",ticker="MIC",entity="Macquarie Infrastructure Company LLC",group="mic",raw_short=True,direction="Long",entry="$14.40",horizon="18~36개월",filename="analysis/ideas/2010/2010-06-03_MIC_long.md",link=None,desc=36804,cat=396,title="ring-fenced debt·Atlantic cash-unlock·$28 Long",verdict="강한 성공 방향 — cash upstream·배당 정상화",score=8.8,process=8.8,
summary="$14.40에서 energy businesses만 약 $20/share, Atlantic은 covenant 때문에 0처럼 가격됐다. 2010/2011 proportional FCF $2.82/$3.52, fully taxed $2.29/$2.78의 10x=$28, Atlantic 회복 포함 bull 약 $46였다.",valuation="IMTT $14~15/share, energy floor 약 $20. Atlantic $838.5m non-recourse debt/$112m LTM EBITDA=7.4x가 2011말 5.3x로 내려가면 6.0x 아래 50%, 5.5x 아래 100% cash upstream이 가능했다.",actual="IMTT repricing·Hawaii 연 $8m rate relief·Atlantic 비용절감과 debt paydown이 holdco cash를 개선해 배당이 재개·확대됐다. 2015초 후속 주가 약 $90가 언급되지만 exact row는 없다.",price="$14.40→$28/$46과 후속 $90은 경로만 판정하며 exact return은 null이다.",drivers="Atlantic debt amortization이 cash-trap threshold를 통과했고 IMTT 3~5년 계약의 20~25% repricing과 Hawaii rate relief가 FCF를 지지했다.",error="energy floor와 FCF의 이중계상, NOL 종료·manager fee, covenant 통과일 sensitivity가 약했다.",first_signal="2011말 Atlantic >6.0x 또는 EBITDA<$112m, IMTT renewal rate 급락 시 $28 base를 철회한다.",metrics=[("Entry/base","$14.40","$28","큰 rerating","성공"),("2011 taxed FCF","$2.78","10x","배당 정상화","성공"),("Atlantic leverage","7.4x","5.3x","cash unlock","성공"),("IMTT","$14~15","20~25% repricing","가치 유지","성공"),("Energy floor","$20","Atlantic free","후속 상회","성공")],timeline=[("2009","Atlantic stress","trap"),("2010-03","7.4x","차단"),("2010-06-03","VIC Long","$14.40"),("2010","Hawaii relief","$8m"),("2011-H2","6.0x gate","upstream"),("2012","distribution 회복","확인"),("2014","IMTT stake","control"),("2015-Q1","후속 $90","rerating")],claimdata=[("energy floor","IMTT·Hawaii만 $20다.","contracted storage·utility","after-tax upstream","FCF -20% 시 반증","cash·valuation 회복","성공","upstreamable FCF로 바꾼다."),("Atlantic unlock","6.0x/5.5x를 통과한다.","$838.5m debt·$112m EBITDA","volume 유지","2011말>6x면 반증","distribution 재개","성공","covenant 전 equity는 option이다."),("IMTT repricing","갱신 rate +20~25%다.","40m+ barrels·3~5년","utilization 유지","volume·rate 동시하락 시 반증","초기 기여","성공","renewal cohort를 본다."),("Hawaii relief","연 $8m EBITDA 증가다.","rate decision","pass-through 안정","disallowance 시 반증","cash 지지","성공","allowed return으로 잰다."),("$28 FCF value","$2.78×10=$28이다.","segment model","tax·capex 정상","FCF<$2.25 시 반증","base 상회","성공","asset cash와 gate를 잇는다."),("$46 bull","Atlantic 회복 시 $46다.","network·long leases","EBITDA 정상","lease loss 시 반증","후속 bull 상회","성공","free option에도 debt를 붙인다.")]),

I(id="6cfacc0d-d187-4c50-b1ce-e08032bcc9bf",date="2012-03-28",author="pokey351",ticker="MIC",entity="Macquarie Infrastructure Company LLC",group="mic",raw_short=True,direction="Long",entry="$32.80",horizon="12~24개월",filename="analysis/ideas/2012/2012-03-28_MIC_long.md",link="https://www.valueinvestorsclub.com/idea/MACQUARIE_INFRASTRUCT_CO_LLC/8791149648",desc=8743,cat=453,title="IMTT 분쟁·Atlantic lock-up 해제의 $50 Long",verdict="성공 — cash upstream과 배당개시",score=8.7,process=9.0,
summary="$32.80에서 2012 proportional FCF/share 약 $4의 8x였다. IMTT 공동소유자 distribution·capex 분쟁과 Atlantic debt lock-up이 풀리면 연 $1.50 dividend, storage repricing·낮은 interest reset으로 $50까지 rerate한다는 Long이다.",valuation="`$4 FCF×8x=$32`가 entry, cash upstream과 4.5% 안팎 dividend가 생기면 12~13x=$48~52다. stated FCF에서 restricted cash·capex reserve·debt service·manager fee·tax를 차감한다.",actual="IMTT governance overhang과 Atlantic lock-up이 완화되며 dividend-paying infrastructure security로 전환했다. 배당과 valuation이 상승해 $50 mechanism이 실현됐다.",price="$32.80·$50만 보존하며 exact total return은 null이다.",drivers="operating recovery가 legal/covenant cash-access catalyst로 좁혀졌고 dispute·lock-up 해제로 holdco discount가 줄었다.",error="$4 proportional FCF와 holdco cash의 차이, 분쟁해결과 board dividend 결정의 별도 확률이 부족했다.",first_signal="2012년 내 분쟁 미해결·Atlantic leverage 재상승·첫 배당 <$1.50 run-rate면 clock을 재설정한다.",metrics=[("Entry/target","$32.80","$50","경로 실현","성공"),("FCF/share","$4","8x→12~13x","배당 rerating","성공"),("Dividend","$0","$1.50","재개·성장","성공"),("IMTT","분쟁","해결","upstream 개선","성공"),("Atlantic","lock-up","해제","cash 증가","성공")],timeline=[("2010","선행 Long","recovery"),("2012-03-28","VIC Long","$32.80"),("2012-H2","renewal","FCF"),("2012","분쟁 완화","gate"),("2012~13","lock-up 해제","upstream"),("2013","배당 상승","확인"),("2014","IMTT buy-in","종결")],claimdata=[("$4 FCF","proportional FCF $4다.","segment model","capex·tax 정확","cash<$3.25 시 반증","배당능력 회복","성공","holdco cash와 reconciliation한다."),("IMTT 분쟁","JV dispute가 끝난다.","협상 진행","governance 합의","2012 미해결 시 반증","완화·후일 buy-in","성공","JV veto discount를 둔다."),("Atlantic unlock","lock-up 종료다.","deleveraging·reset","cash flow 유지","leverage 재상승 시 반증","upstream 정상화","성공","covenant가 첫 행이다."),("$1.50 dividend","annual $1.50 시작이다.","cash access","payout willingness","첫 2회 미달 시 반증","배당 현실화","성공","capacity와 willingness를 나눈다."),("renewal repricing","H2 갱신이 2013 FCF를 높인다.","maturity cohort","utilization 유지","volume이 rate 상쇄 시 반증","초기 기여","성공","rate×volume을 본다."),("$50 rerating","8x가 12~13x다.","visible dividend","risk premium 하락","배당 후 <9x면 반증","mechanism 작동","성공","multiple을 event에 연결한다.")]),

I(id="ce69d200-e844-4501-acc4-71bfd0f04451",date="2014-01-13",author="cameron57",ticker="MIC",entity="Macquarie Infrastructure Company LLC",group="mic",raw_short=True,direction="Long",entry="$51.63",horizon="12개월",filename="analysis/ideas/2014/2014-01-13_MIC_long.md",link=None,desc=21025,cat=80,title="$3.75+ 배당·IMTT capex 정상화의 $70 Long",verdict="성공 — dividend growth·IMTT control rerating",score=8.8,process=8.5,
summary="$51.63에서 contracted cash flow와 2014 dividend $3.75+, 약 7%대 yield를 샀다. IMTT expansion capex가 현금화되고 target 5.5% yield를 받으면 $68~70, 배당 포함 약 40%였다.",valuation="`$3.75/5.5%=$68.18`. 배당은 `asset FCF-capex-interest-tax-manager fee-debt reserve`보다 클 수 없다. IMTT 잔여 50% buy-in은 purchase debt를 뺀 per-share accretion으로 본다.",actual="IMTT capex가 FCF로 전환되고 배당이 늘었다. 2014 잔여 IMTT 50%를 약 $1.025bn에 인수했고 2015초 후속 가격 약 $90가 언급된다.",price="$51.63·$70·40%는 원문 목표이며 exact 1년 IRR은 null이다.",drivers="capex cash conversion·dividend guide·IMTT control이 governance discount와 yield를 낮췄다.",error="5.5% yield에 rate beta·coverage·renewal concentration, buy-in funding과 fee 증가 sensitivity가 부족했다.",first_signal="dividend<$3.75 또는 payout>90%, IMTT EBITDA ramp 2Q 지연 시 target을 폐기한다.",metrics=[("Entry/target","$51.63","$68~70","후속 $90","성공"),("Dividend","$3.75+E","증가","증가","성공"),("Yield","7%대","5.5%","compression","성공"),("IMTT capex","elevated","cash conversion","control 확대","성공"),("Return","40%","12개월","exact null","방향 성공")],timeline=[("2012","배당재개","access"),("2014-01-13","VIC Long","$51.63"),("2014-H1","capex ramp","FCF"),("2014-07","50% buy-in","control"),("2014-H2","dividend 상승","rerating"),("2015-Q1","후속 $90","target 초과"),("2017","payout 성숙","risk")],claimdata=[("$3.75 dividend","최소 $3.75다.","segment FCF","coverage 충분","payout>90% 시 반증","성장 실현","성공","coverage bridge부터 쓴다."),("5.5% rerating","$68+ 가치다.","infra comps","rate 안정","risk premium 급등 시 반증","target 상회","성공","duration을 stress한다."),("capex 정상화","확장투자가 cash를 만든다.","tank contracting","on-time lease-up","2Q 지연 시 반증","cash conversion","성공","contracted yield로 본다."),("IMTT buy-in","50% 매입이 accretive다.","control 가치","yield>funding","per-share 희석 시 반증","$1.025bn 거래","성공","control·financing을 함께 둔다."),("Atlantic 안정","FBO가 배당을 지킨다.","long leases","GP 안정","same-store GP 하락 시 반증","당시 기여","성공","gallons보다 GP·lease다."),("12M 40%","dividend+rerating이다.","$70 target","1년 내 catalyst","연말 미달 시 반증","후속 초과","성공","target과 exact IRR을 나눈다.")]),

I(id="a6090a5e-b8a4-43d5-94a5-164fc05f3f89",date="2017-10-04",author="gandalf",ticker="MIC",entity="Macquarie Infrastructure Corporation",group="mic",raw_short=True,direction="Long",entry="원문 고배당 가격대",horizon="12~24개월",filename="analysis/ideas/2017/2017-10-04_MIC_long.md",link="https://www.valueinvestorsclub.com/idea/MACQUARIE_INFRASTRUCTURE_CP/3453478175",desc=0,cat=58,title="7.6% yield·10% FCF growth의 $95 Long",verdict="강한 실패 — IMTT utilization shock·dividend cut",score=2.5,process=6.8,
summary="2012~17 FCF/share CAGR 16%, 2018E FCF $6.49, FCF yield 9%·dividend yield 7.6%를 근거로 10% growth와 $95를 제시했다. 장기계약의 renewal·product-flow risk를 과소평가했다.",valuation="$6.49×14.6x 또는 $5.76 annual dividend의 yield compression으로 $95다. segment별 `renewal volume×rate-capex-debt service`로 payout survival을 먼저 봐야 했다.",actual="2018 IMTT utilization이 약 96%대에서 88.1%로 급락했고 quarterly dividend가 $1.44→$1.00, 31% cut됐다. yield floor와 주가가 함께 무너졌다.",price="performance row는 없지만 horizon과 mechanism 모두 강한 실패다; exact return은 null이다.",drivers="tank renewal failure가 utilization·rate·FCF를 동시에 낮추고 board가 balance sheet 보호를 위해 payout을 잘랐다.",error="과거 CAGR을 영구화하고 growth capacity와 legacy deterioration을 분리하지 않았으며 manager alignment를 과신했다.",first_signal="utilization<92%, renewal volume·rate 동시악화 또는 coverage<1.1x면 즉시 폐기한다.",metrics=[("FCF/share","$6.49E","+10%","하향","실패"),("Dividend yield","7.6%","floor","$1.44→$1.00","치명적 실패"),("FCF yield","9%","rerating","coverage 악화","실패"),("Utilization","96%대","안정","88.1%","강한 실패"),("Target","고배당 가격","$95","급락","강한 실패")],timeline=[("2012~17","FCF CAGR 16%","외삽"),("2017-10-04","VIC Long","$95"),("2017-Q4","renewal weakness","break"),("2018-02","dividend cut","반증"),("2018-Q1","88.1%","확인"),("2018","주가 급락","floor 소멸"),("2019-10","review","thesis 종료")],claimdata=[("IMTT 안정","장기계약이 FCF를 지킨다.","90%+ history","renewal 유지","<92%면 반증","88.1%","강한 실패","만기벽을 본다."),("10% growth","16% 뒤 10% 지속이다.","expansion capex","growth>decline","2Q 하향 시 반증","weakness가 압도","실패","cohort별 capex로 나눈다."),("7.6% floor","배당이 downside다.","$5.76 payout","board 유지","coverage<1.1x 시 반증","31% cut","치명적 실패","high yield는 cut 확률이다."),("manager alignment","high-water mark가 주주와 같다.","stock ownership","fee·value 일치","fee 유지·cut 시 반증","손실 못 막음","부분 실패","인센티브는 operating hedge가 아니다."),("diversification","Atlantic/Hawaii가 흡수한다.","FBO·utility","cash source 분산","한 segment가 payout 깨면 반증","IMTT만으로 cut","실패","marginal cash 집중도로 잰다."),("$95","FCF·yield로 $95다.","$6.49·10%","동시상승","cut 시 폐기","급락","강한 실패","target 전 survival tree다.")]),

I(id="ddc3442c-ff16-4b1d-a92d-216ab9c3a0f7",date="2019-11-01",author="rii136",ticker="MIC",entity="Macquarie Infrastructure Corporation",group="mic",raw_short=True,direction="Long",security="Common / asset-sale distribution claim",entry="약 $43",horizon="약 1년",filename="analysis/ideas/2019/2019-11-01_MIC_strategic_alternatives_long.md",link=None,desc=19676,cat=175,title="$52~66 strategic-alternatives Long",verdict="강한 성공 — 전 자산 매각·분배, clock 지연",score=9.0,process=9.1,
summary="2017 dividend compounder를 liquidation으로 재분류했다. 약 $43에서 review와 private storage/FBO multiples로 sale value $52~66, 3Q dividend 포함 1년 25~60%를 봤다. manager의 13m주·$550m 지분과 fee 변화가 sale incentive를 강화했다.",valuation="asset EBITDA×transaction multiple에서 debt·tax·1% cost·disposition fee를 뺀다. no-sale mid-$40s, Atlantic 10~12x+, storage 10~13x, IMTT 2020 uplift $38~80m였다. 9.5% dividend는 sale 전 carry다.",actual="IMTT를 약 $2.67bn에 팔아 $11/share를 지급했고 Atlantic을 $4.475bn에 팔아 $37.386817/unit을 분배했다. Hawaii도 후속 매각됐지만 전체 clock은 1년보다 길었다.",price="$11+$37.386817만 $48.386817이지만 ex-date price·일반배당·LLC·tax series가 없어 exact IRR은 null이다.",drivers="buyer universe와 board/manager incentive, asset별 sale이 public discount를 현금으로 바꿨다. IMO uplift가 완전히 맞을 필요도 없었다.",error="모든 sale을 1년에 압축했고 IMO uplift·regular dividend를 낙관했다. tax basis·fee sensitivity가 더 필요했다.",first_signal="6개월 내 banker·buyer evidence 부재 또는 after-tax floor<$44·dividend cut이면 1년 IRR을 철회한다.",waterfall="sale EV에서 debt·tax·transaction·manager fee·wind-down을 빼고 실제 분배일 common/LLC cash만 payoff다.",metrics=[("Entry/sale","$43","$52~66","asset sales","강한 성공"),("Yield","9.5%","3Q carry","liquidation 전환","부분"),("IMTT sale","public discount","private","$2.67bn","성공"),("IMTT distribution","없음","cash","$11","성공"),("Atlantic distribution","SOTP","private","$37.386817","강한 성공")],timeline=[("2018-02","cut","compounder 붕괴"),("2019-10","review","event"),("2019-11-01","VIC Long","$43"),("2020-11","IMTT deal","$2.67bn"),("2020-12","close","cash"),("2021-01","$11","분배"),("2021-06","Atlantic deal","$4.475bn"),("2021-09","$37.386817","payoff"),("2022","Hawaii","종결")],claimdata=[("review 실행","board가 매각한다.","공식 review·incentives","buyers 존재","6개월 evidence 부재 시 반증","세 자산 매각","강한 성공","첫 sale이 credibility다."),("IMTT private value","buyer가 높게 산다.","10~13x deals","weakness 일시적","bid<floor 시 반증","$2.67bn","성공","buyer EV로 검증한다."),("IMO uplift","EBITDA +$38~80m다.","segregation·contango","수요 지속","utilization 미개선 시 반증","sale에는 비핵심","부분","theme와 sale floor를 나눈다."),("Atlantic multiple","10~12x+다.","Signature·Landmark","traffic·lease 안정","bid<10x 시 반증","$4.475bn","강한 성공","active auction comp가 강하다."),("proceeds 분배","sale cash가 주주에게 온다.","ownership·fee termination","재투자 안 함","분배 지연 시 반증","$11+$37.386817+residual","강한 성공","calendar까지 쓴다."),("1년 25~60%","1년에 완료다.","review","delay 없음","12개월 미close 시 반증","전체는 지연","방향 성공/시간 실패","value와 IRR을 나눈다.")]),

I(id="770d0a70-f908-4b5d-a0fd-4ad0b2eb76a6",date="2021-04-16",author="althea",ticker="MIC",entity="Macquarie Infrastructure Corporation / MIC LLC",group="mic",raw_short=False,direction="Long",security="Common→LLC units / liquidation distributions",entry="약 $3.7bn EV",horizon="Atlantic 6개월·Hawaii 12개월+",filename="analysis/ideas/2021/2021-04-16_MIC_liquidation_long.md",link="https://www.valueinvestorsclub.com/idea/MACQUARIE_INFRASTRUCTURE_CP/9439712255",desc=20001,cat=59,title="Atlantic 6개월·tax-efficient liquidation Long",verdict="매우 성공 — 52일 내 $4.475bn deal·$37.386817 분배",score=9.7,process=9.5,
summary="IMTT sale 뒤 Atlantic·Hawaii만 남았다. Signature $5.58bn auction을 active comp로 Atlantic 14.5x 2019 EBITDA, Hawaii $540m/9x로 평가했고 LLC 전환이 Atlantic-first tax-efficient sale을 가능하게 해 6개월 catalyst를 예상했다.",valuation="Atlantic base 14.5x EBITDA/15.4x EBITDA-maintenance capex, bear 12.5x/13.3x. Hawaii $540m/9x에서 1% cost+$10m wind-down+manager fee를 차감했다. no-sale $26은 Atlantic 10.5x·Hawaii 6x다.",actual="게시 52일 뒤 2021-06-07 KKR $4.475bn sale이 발표되고 9월 close 뒤 $37.386817/unit이 분배됐다. Hawaii는 더 오래 걸렸다.",price="공식 분배는 확인되지만 entry·IMTT basis·Hawaii final cash가 연결되지 않아 exact IRR은 null이다.",drivers="첫 sale·분배라는 revealed preference, Signature bidding war, LLC tax 구조와 Atlantic의 69개 base·long leases·hangar·low capex가 edge였다.",error="Hawaii regulatory/tax와 Atlantic 14.5x downside probability를 더 넓게 봐야 했다.",first_signal="2021-10 무agreement·LLC tax 지연·bid<12.5x면 핵심 IRR을 폐기한다.",waterfall="sale EV에서 debt·tax·1% cost·manager fee·$10m wind-down을 빼고 분배일별 unit cash를 기록한다.",metrics=[("Catalyst","6개월","sale","52일","매우 성공"),("Multiple","14.5x","Signature 할인","$4.475bn","성공"),("Distribution","미정","대규모","$37.386817","강한 성공"),("Hawaii","$540m/9x","12개월+","후속 sale","성공"),("Costs","1%+$10m+fee","차감","proceeds 반영","성공")],timeline=[("2020-11","IMTT deal","credibility"),("2021-01","$11","payout"),("2021-02","Signature $5.58bn","comp"),("2021-04-16","VIC Long","clock"),("2021-06-07","$4.475bn","52일"),("2021-09-23","close","cash"),("2021-10","$37.386817","payoff"),("2022","Hawaii","residual")],claimdata=[("6개월 sale","agreement가 6개월 내다.","첫 sale·LLC·auction","diligence 준비","2021-10 미발표 시 반증","52일","매우 성공","deadline을 둔다."),("14.5x value","Signature보다 소폭 할인이다.","14.6x/15.9x comp","scale discount 상쇄","bid<12.5x 시 반증","$4.475bn","성공","metric을 맞춘다."),("durable FBO","long lease·hangar·low capex다.","2007~20 positive FCF","traffic 회복","GP·tenure 급락 시 반증","buyer가 인정","성공","gallons보다 GP·lease다."),("LLC tax","Atlantic-first tax를 낮춘다.","reorganization","vote·opinion 통과","큰 leakage 시 반증","실행","성공","tax도 core claim이다."),("Hawaii","9x/$540m다.","utility·propane","tourism·PUC","6x 이하 시 반증","후속 sale","성공","residual duration을 나눈다."),("downside","no-sale $26다.","10.5x/6x implied","FCF 유지","구조하락 시 반증","sale로 미시험","미발생","failed-sale gap도 둔다.")]),

I(id="c2cc8c96-b700-4adb-8c4f-1fdd6ecd8473",date="2010-03-11",author="britt12",ticker="MSG",entity="The Madison Square Garden Company",group="msg",raw_short=False,direction="Long",entry="spin 직후 가격대",horizon="2~5년",filename="analysis/ideas/2010/2010-03-11_MSG_long.md",link=None,desc=30137,cat=122,title="RSN cash+teams·Garden free option Long",verdict="강한 SOTP 성공 — 2015·2020 분할",score=9.0,process=8.7,
summary="Cablevision spin 직후 forced selling과 Dolan discount를 이용했다. MSG/MSG+ affiliate-fee FCF로 $30+를 지지하고 Knicks·Rangers·Garden을 낮게 잡아 private-value $50까지 열었다. sports headline이 아니라 RSN cash engine이 downside anchor다.",valuation="media는 affiliate fee·광고-rights·overhead의 FCF, sports는 revenue multiple-league debt, venue는 renovation capex를 차감한다. $30~50 사이 control·governance·tax haircut이 필요하다.",actual="2015 구 MSG 3주당 신 sports/entertainment MSG 1주가 분배됐고 2020 MSGS 1주당 MSGE 1주가 분배돼 media·sports·entertainment가 별도 security가 됐다.",price="두 spin과 배당을 잇는 performance row가 없어 exact total return은 null이다.",drivers="forced selling과 exclusive rights/affiliate escalator가 낮은 entry·recurring cash를 만들고 separations가 conglomerate discount를 증권화했다.",error="subscriber·affiliate rate 대 rights-cost 충돌, renovation overrun·Dolan control, private value의 minority haircut을 더 stress해야 했다.",first_signal="rights cost·subscriber decline이 rate보다 빠르거나 renovation>$850m·net debt 증가 시 $30 floor를 재산정한다.",waterfall="affiliate·ticket·venue cash에서 rights·payroll·renovation·debt·overhead를 빼고 2015 3:1·2020 1:1 분배를 연결한다.",metrics=[("Conservative","spin 직후","$30+","분할","성공"),("Private SOTP","discount","$50","scarcity 확인","성공"),("2015","통합 MSG","unlock","3:1","성공"),("2020","sports+ent","unlock","1:1 MSGE","성공"),("Return","복수증권","합산","row 없음","null")],timeline=[("2010-02","Cablevision spin","forced selling"),("2010-03-11","VIC Long","$30/$50"),("2010~13","renovation","capex"),("2015-09-30","신 MSG 분배","3:1"),("2015-10-01","MSG·MSGN 거래","media"),("2020-04-17","MSGE 분배","1:1"),("2020-04-20","MSGS·MSGE 거래","완성")],claimdata=[("RSN cash","media가 $30+를 지지한다.","exclusive rights·affiliate contracts","rate>rights cost","FCF 2년 하락 시 반증","MSGN 분리","성공","subs×rate-rights로 본다."),("sports option","teams implied value가 낮다.","scarce franchises","minority discount 제한","team losses 확대 시 반증","MSGS 증권화","성공","debt·control을 뺀다."),("Garden","renovation 뒤 가치가 유지된다.","iconic venue","NPV>overrun","budget>$850m 시 반증","MSGE 핵심","성공","capex를 NPV로 본다."),("overhang","forced seller가 일시적이다.","mandate mismatch","inventory finite","volume 정상화 뒤 할인 시 반증","discovery 진행","성공","seller 규모·종료를 적는다."),("Dolan discount","governance가 destruction은 아니다.","discount 반영","actions 가능","leakage·미분리 시 반증","두 번 분할","성공","행동확률로 모델링한다."),("$50 SOTP","순가치가 $50다.","media+teams+venue","haircut 충분","net<$30 시 반증","mechanism 적중","사업 성공/수익 미검증","SOTP와 return을 나눈다.")]),

I(id="8ef6f3c0-b00d-405e-bcb5-ec88ac02f83e",date="2010-06-22",author="flyer",ticker="MSG",entity="The Madison Square Garden Company",group="msg",raw_short=False,direction="Long",entry="$20 이하·$22 이하 추가",horizon="18~36개월",filename="analysis/ideas/2010/2010-06-22_MSG_long.md",link=None,desc=34730,cat=3273,title="$30m RSN EBITDA·$23/$46 Long",verdict="강한 성공 — core cash·분할 적중, LeBron 불필요",score=9.2,process=9.3,
summary="$20 아래에서 forced selling·coverage 부재로 할인됐고 2010 Cablevision·DirecTV 계약이 연 $30m incremental EBITDA와 $4~5/share를 만든다고 봤다. 최대 $850m renovation을 당일 차감해도 downside $23, upside $46이었다.",valuation="$30m×8~12x=$240~360m EV, $4~5/share다. $775~850m capex는 2년+ 지출이라 전액 T0 차감이 보수적이다. sports·venue private value에서 debt·tax·Dolan discount를 뺀다.",actual="media cash power가 드러나 2015 MSGN이 분리됐다. LeBron은 오지 않았지만 core는 생존했고 2020 sports/entertainment도 분리됐다.",price="$20/$22와 $23/$46은 원문 anchor; successor series가 없어 exact return은 null이다.",drivers="이미 체결된 affiliate 계약의 accounting lag와 forced seller 종료가 edge였다. optional star가 실패해도 cash engine이 남았다.",error="$30m의 rights-cost step-up·subscriber·tax bridge가 더 필요했다. renovation PV의 보수성과 value-enhancing return을 attribution해야 했다.",first_signal="affiliate uplift<$30m 또는 incremental margin<70%, renovation>$850m이면 $23 floor를 폐기한다.",waterfall="RSN EBITDA를 after-tax FCF로 바꾸고 renovation cash를 할인한 뒤 2015 3:1·2020 1:1 분배를 더한다.",metrics=[("Entry","<$20","add<$22","unlock","성공"),("Down/up","$23","$46","분할 확인","성공"),("RSN EBITDA","$30m","$4~5/share","media 분리","성공"),("Capex","$775~850m","≤$850m","완료","성공"),("Spins","통합","recognition","2015·2020","강한 성공")],timeline=[("2010-01","RSN 계약","$30m"),("2010-02","spin","overhang"),("2010-06-22","VIC Long","$20"),("2010-07","LeBron 타팀","optional 실패"),("2010~13","renovation","capex"),("2015-09","media spin","core"),("2020-04","sports/ent spin","SOTP")],claimdata=[("$30m RSN","계약이 $30m EBITDA다.","Cablevision·DirecTV","cost 작음","margin<70% 시 반증","media 독립가치","성공","revenue·cost·tax로 검증한다."),("forced selling","mandate 매도가 끝난다.","$1.7bn cap mismatch","finite","할인 지속 시 반증","recognition 확대","성공","seller inventory를 추정한다."),("coverage","이해가 discount를 줄인다.","analyst 공백","estimate 개선","coverage 후 무변화 시 반증","separation이 해결","성공","분할이 더 강한 catalyst다."),("capex≤$850m","최대 차감 후도 upside다.","$775~850m","overrun 제한",">$850m 시 반증","upgrade 완료","성공","PV·overrun·FCF를 나눈다."),("Knicks star","stars가 revenue를 높인다.","2010 cap space","유치 성공","부재 시 제거","LeBron 부재에도 생존","실패/비핵심","optional 실패에도 base가 산다."),("$23/$46","보수 SOTP도 가격보다 높다.","세 가치층","haircut 충분","net<$23 시 반증","두 번 분할","성공","ratio까지 추적한다.")]),

I(id="6339c03d-166b-4ac3-8557-fa9d61034dad",date="2010-12-22",author="Rotin",ticker="MSG",entity="The Madison Square Garden Company",group="msg",raw_short=True,direction="Long",entry="약 $24.50",horizon="2012년말",filename="analysis/ideas/2010/2010-12-22_MSG_long.md",link="https://www.valueinvestorsclub.com/idea/Madison_Square_Garden/8375635833",desc=0,cat=485,title="<10x pro-forma FCF·$37 Long",verdict="성공 방향 — FCF·SOTP 적중, 23% IRR 미검증",score=8.8,process=9.0,
summary="$24.50에서 renovation 반영 pro-forma FCF가 10x 미만이고 15x를 주면 2012년말 $37, 50% total/23% IRR이다. $50+ SOTP는 cross-check, base는 recurring media FCF였다.",valuation="`normalized FCF/share×15=$37`. $50+ SOTP는 media·teams·venue에서 renovation debt·overhead·tax·control discount를 뺀다. FCF와 SOTP를 중복하지 않고 base/cross-check로 나눴다.",actual="media cash와 trophy assets는 가치를 유지했고 2015·2020 separations가 SOTP를 securities로 만들었다. renovation도 완료됐지만 exact 2012 price는 미복원이다.",price="$24.50·$37·50%/23%는 원문 수치; exact return은 null이다.",drivers="높은 FCF yield가 downside를 제공하고 separations가 value discovery를 만들었다. team performance보다 affiliate economics가 core였다.",error="normalized FCF의 renovation·rights·payroll 기간, 15x/rate sensitivity와 private SOTP minority discount가 부족했다.",first_signal="FCF yield<8% 또는 FCF/share 두 번 하향·capital action 부재면 $37 clock을 재승인한다.",waterfall="normalized FCF에서 rights·payroll·renovation debt service를 빼고 2015 3:1·2020 1:1 분배를 합산한다.",metrics=[("Entry/target","$24.50","$37","mechanism 실현","성공"),("FCF multiple","<10x","15x","media 가치","성공"),("Expected","50%","23% IRR","row 없음","미검증"),("SOTP","$50+","cross-check","두 분할","성공"),("Renovation","pro forma","improvement","완료","성공")],timeline=[("2010-02","spin","standalone"),("2010-03/06","선행 Longs","framework"),("2010-12-22","VIC Long","$24.50"),("2011~13","renovation","FCF test"),("2012-12","target date","미복원"),("2015-09","MSGN spin","media"),("2020-04","MSGE spin","sports/venue")],claimdata=[("<10x FCF","renovation 후도 싸다.","media cash·pro forma capex","정상화 정확","FCF -20% 시 반증","media 가치 확인","성공","포함항목을 고정한다."),("15x/$37","quality FCF는 15x다.","RSN duration","discount 축소","2012말<12x면 반증","장기 unlock·단기 미복원","방향 성공","multiple과 날짜를 나눈다."),("renovation ROI","capex가 venue를 높인다.","phased spend","overrun 제한","budget 초과 시 반증","완료·핵심 유지","성공","maintenance와 enhancement를 나눈다."),("Knicks/ratings","team이 ticket·ratings를 높인다.","large market","performance 지속","payroll만 상승 시 반증","volatile·비핵심","부분","team을 base에 넣지 않는다."),("Dolan discount","action 가능성이 있다.","discounted value","분할 허용","미분리 시 반증","두 번 분할","성공","행동으로 평가한다."),("$50+ SOTP","세 자산 순가치 $50+다.","comps","haircut 후도 남음","net<base 시 반증","별도 securities","성공","FCF와 중복하지 않는다.")])
]

def sources(i): return [m.S("첨부 SQL 원문·metadata",i["link"],"VIC_IDEAS(4).sql / VIC",i["date"],f"idea_id·raw direction·description {i['desc']} chars·catalyst {i['cat']} chars","원문"),*m.SOURCES[i["group"]]]
def report(i):
 old=m.idea_sources; m.idea_sources=sources
 try: t=m.report(i)
 finally: m.idea_sources=old
 raw="Short" if i["raw_short"] else "Long"; generic="회계이익에서 운전자본·담보·규제자본·maintenance/growth investment·interest·tax를 차감하고, common보다 선순위인 계약·채권자 청구권을 먼저 배치한다. 자산가치와 계약상 수취액은 현금화 날짜·세금·재투자 의무를 반영한다. 기업가치가 맞아도 security와 duration이 틀리면 투자결과는 실패할 수 있다."
 t=t.replace("Batch 046 canonical report.","Batch 051 canonical report.").replace("### Common equity cash waterfall","### Security cash waterfall").replace(generic,i["waterfall"])
 t=t.replace("이번 10건은 첨부 SQL에 performance row가 없으므로 1개월~5년 수익률을 만들지 않는다. 사건 성공, 기업 생존, target 도달과 투자 total return을 각각 별도 필드로 둔다. corporate action이 있으면 successor security까지 연결돼야 정확한 IRR을 계산할 수 있다.","첨부·repository에 정확한 performance row가 없다. 기업·사건 결과와 security total return을 분리하며 배당·청산분배·successor shares를 날짜별로 복원하기 전 return과 IRR은 null이다.")
 t=t.replace(f"`ATH`를 회사로 보지 말고 {i['entity']} 법인·exchange·날짜로 고정한다.",f"`{i['ticker']}`와 날짜를 {i['entity']}의 실제 법인·security에 고정한다.")
 t=t.replace(f"| 회사 / 원 ticker | {i['entity']} / {i['ticker']} |",f"| 회사 / 원 ticker | {i['entity']} / {i['ticker']} |\n| 실제 Security | **{i['security']}** |")
 return t

def payload():
 old=m.idea_sources; m.idea_sources=sources
 try: p=m.make_payload(IDEAS)
 finally: m.idea_sources=old
 p["batch"]=51; p["title"]="Genworth MI Canada / Macquarie Infrastructure / Madison Square Garden — Entity, Cash Access and Separation V9"
 for i,a,b in zip(IDEAS,p["ideas_master"],p["postmortems"]): a["security_ko"]=i["security"]; a["performance_available"]=0; b["research_direction_ko"]=f"{i['direction']} / {i['security']}"; b["research_status_ko"]="SQL·공식 사건 검증; exact return null"; b["confidence"]=.92 if i["desc"] else .86
 return p

def index():
 rows=[]
 for n,i in enumerate(IDEAS,1):
  raw="Short" if i["raw_short"] else "Long"; link=Path(i["filename"]).relative_to("analysis")
  rows.append(f"| {n} | {i['date']} | {i['entity']} | {raw}→**{i['direction']}** | {i['verdict']} | [{i['title']}]({link}) |")
 return "\n".join(["# Batch 051 — Genworth MI Canada / Macquarie Infrastructure / Madison Square Garden — V9 Index","",f"> Research as-of {ASOF}. 첨부 SQL의 원문·catalyst를 감사했다. **10 idea = 10 canonical reports**이며 없는 성과는 만들지 않았다.","","## 0. 배치 결론","","2009 `MIC`는 캐나다 mortgage insurer, 2010~2021 `MIC`는 미국 infrastructure holding company다. Macquarie는 2010~14 `자회사 FCF→debt paydown→cash unlock→배당→yield rerating`, 2017 `yield trap`, 2019~21 `asset sale→after-tax distribution`으로 프레임이 바뀐다. MSG는 2015·2020 분할로 media·sports·entertainment 세 증권이 된 SOTP 실험이다.","","## 1. Idea Units","","| # | 날짜 | 실제 회사 | raw→연구 방향 | 판정 | Canonical report |","|---:|---|---|---|---|---|",*rows,"","## 2. Entity / Direction Audit","","10건 모두 실제 Long이다. raw Short 7건과 2009 MIC entity를 교정했다. 2019·2021 MIC는 asset-sale/liquidation distribution claim이며 MSG 성과는 2015 3:1·2020 1:1 successor shares를 이어야 한다.","","## 3. 투자논지 누적 교정","","Genworth는 housing 예측보다 recourse·은행 underwriting·capital이 핵심이었다. Macquarie는 자회사 FCF의 위치가 holdco dividend를 결정했고 2017 yield trap 이후 net sale proceeds로 전환해 성공했다. MSG는 RSN FCF를 downside, teams·venue를 option으로 둔 뒤 실제 분할로 검증됐다.","","## 4. 공통 교훈","","1. Ticker보다 법인·날짜가 먼저다.\n2. 자회사 FCF와 holdco cash는 다르다.\n3. 높은 yield는 cut 확률일 수 있다.\n4. 실패한 compounder도 liquidation으로 다시 살 수 있다.\n5. sale EV에서 debt·tax·fees를 뺀다.\n6. SOTP의 최강 촉매는 실제 분할이다.\n7. optional catalyst 실패에도 base가 살아야 한다.\n8. 사건 성공과 exact return을 분리한다.","","## 5. 산출물","","- Payload: `data/curated/batch_051_mic_msg_deep_v7.json`\n- Wrapper: `analysis/batch_051_mic_msg_10.md`\n- Source packet: `data/curated/batch_051_source_packet.json`\n- Builder: `scripts/51_build_batch_051_v9.py`",""])

def main():
 assert len(IDEAS)==10 and len({i["id"] for i in IDEAS})==10
 for i in IDEAS:
  assert len(i["claims"])==6 and len(i["metrics"])==5 and len(i["timeline"])>=6
  q=ROOT/i["filename"]; q.parent.mkdir(parents=True,exist_ok=True); q.write_text(report(i),encoding="utf-8")
 parts=[str(Path(i["filename"]).relative_to("analysis")) for i in IDEAS]
 (ROOT/"analysis/batch_051_mic_msg_10.md").write_text("# Batch 051 — Genworth MI Canada / Macquarie Infrastructure / Madison Square Garden V9\n\n<!-- batch_parts: "+"|".join(parts)+" -->\n\n> Streamlit wrapper. [V9 Index](batch_051_v9_index.md).\n",encoding="utf-8")
 (ROOT/"analysis/batch_051_v9_index.md").write_text(index(),encoding="utf-8")
 p=payload(); (ROOT/"data/curated/batch_051_mic_msg_deep_v7.json").write_text(json.dumps(p,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 packet={"batch":"051","format":"V9-per-idea","source":"VIC_IDEAS(4).sql + official filings","record_count":10,"direction_corrections":7,"entity_corrections":1,"performance_rows_found":0,"performance_rule":"corporate action is not exact return","candidates":[{"idea_id":i["id"],"date":i["date"],"ticker":i["ticker"],"company_name":i["entity"],"author":i["author"],"raw_direction":"Short" if i["raw_short"] else "Long","research_direction":i["direction"],"security":i["security"],"description_chars":i["desc"],"catalyst_chars":i["cat"],"performance_available":False,"canonical_report":i["filename"]} for i in IDEAS]}
 (ROOT/"data/curated/batch_051_source_packet.json").write_text(json.dumps(packet,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 inv={"source_filename":"VIC_IDEAS(4).sql","attachment_bytes_checked":122499072,"records_selected":10,"raw_descriptions_present":8,"raw_catalysts_verified":10,"performance_rows_found":0,"direction_corrections":7,"entity_corrections":1,"note":"corporate actions are not exact returns"}
 (ROOT/"data/curated/batch_051_sql_inventory.json").write_text(json.dumps(inv,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 print({k:len(p[k]) for k in ("ideas_master","postmortems","sections","claims","metrics","timeline","sources")})
if __name__=="__main__": main()
