#!/usr/bin/env python3
import json
from pathlib import Path
R=Path(__file__).resolve().parents[1]; J=R/'data/curated/batch_033_pico_grace_deep_v7.json'; M=R/'analysis/batch_033_pico_grace_10.md'; REG=R/'app/components/batch_report.py'
ideas=[
('b0eef45b-dd68-4a53-b0b4-ff341cacfd3d','2009-11-29',2009,'PICO','PICO HOLDINGS INC','vanbr707','Long','https://www.valueinvestorsclub.com/idea/PICO_HOLDINGS_INC/4808531709'),
('e434a54e-c727-4108-b542-f638dc32a374','2011-01-13',2011,'PICO','PICO HOLDINGS INC','kalman951','Long','https://www.valueinvestorsclub.com/idea/PICO_HOLDINGS_INC/3756614642'),
('6124d1de-47ec-4471-a9e5-c05908e7f20c','2013-05-11',2013,'PICO','PICO HOLDINGS INC','seeker','Long','https://www.valueinvestorsclub.com/idea/PICO_HOLDINGS_INC/2869994638'),
('7409b41c-8139-4a67-854c-c1e72c9528a4','2014-02-04',2014,'PICO','PICO HOLDINGS INC','dman976','Long','https://www.valueinvestorsclub.com/idea/PICO_HOLDINGS_INC/2330321377'),
('3cc091ad-fd8f-4ce0-b133-43f5e20406fc','2015-05-05',2015,'PICO','PICO HOLDINGS INC','kiss534','Long',None),
('d80c3e42-9de6-4a0d-b44d-5b7e818b3ed6','2015-11-23',2015,'PICO','PICO HOLDINGS INC','TR1898','Long',None),
('01021a69-9067-48f1-b24d-5107486b8903','2016-08-15',2016,'PICO','PICO HOLDINGS INC','mojoris','Long',None),
('527b25be-7a00-4303-8720-2593189c93b4','2018-11-30',2018,'PICO','PICO HOLDINGS INC','AltaRocks','Long',None),
('3ec8f243-7c36-4af5-bd2d-3976b5a8761f','2006-03-06',2006,'GRA','GRACE (W R) & CO','vincent975','Short','https://www.valueinvestorsclub.com/idea/WR_Grace/0545332608'),
('b29604b6-bd7a-480e-abe7-7b0119a99194','2012-01-17',2012,'GRA','GRACE (W R) & CO','jon64','Long',None)]
SRC={
'p15':'https://www.sec.gov/Archives/edgar/data/830122/000083012216000132/pico1231201510k.htm','p17':'https://www.sec.gov/Archives/edgar/data/830122/000083012218000010/pico1231201710k.htm','p17pr':'https://www.sec.gov/Archives/edgar/data/830122/000083012217000099/ex991picopressreleaseq2201.htm','p19':'https://www.sec.gov/Archives/edgar/data/830122/000083012220000010/pico1231201910k.htm','p21':'https://www.sec.gov/Archives/edgar/data/830122/000083012222000009/vwtr-20211231.htm','p22':'https://www.sec.gov/Archives/edgar/data/830122/000119312522105017/d200860dex991.htm','ucp':'https://www.sec.gov/Archives/edgar/data/1572684/000119312517220761/d391974ddefm14a.htm','dhi':'https://www.sec.gov/Archives/edgar/data/882184/000088218422000152/dhi-20220630.htm','g12':'https://www.sec.gov/Archives/edgar/data/1045309/000104530913000015/gra-20121231x10k.htm','g08':'https://www.sec.gov/Archives/edgar/data/1045309/000104746908009003/a2187162z10-q.htm','g14':'https://www.sec.gov/Archives/edgar/data/1045309/000104530914000057/gra-20141q10xq.htm','g18':'https://www.sec.gov/Archives/edgar/data/1045309/000104530919000025/a201810-k.htm','g21':'https://www.sec.gov/Archives/edgar/data/1045309/000114036121014196/nc10023607x1_ex99-1.htm','g21q':'https://www.sec.gov/Archives/edgar/data/1045309/000104530921000086/gra-20210630.htm'}
desc={'PICO':'PICO Holdings는 여러 비상장·상장 자산을 보유하던 holding company였고, 핵심 자산은 미국 남서부의 water rights·storage를 개발·매각하는 Vidler Water와 한때 주택개발사 UCP였다. 장기 가치는 회계상 earnings보다 water asset의 승인·개발·매각가격, UCP 지분가치, corporate burn, 세금/NOL, 자사주·특별배당 등 자본환원에 좌우됐다. 2021년 Vidler Water Resources로 사명을 바꾼 뒤 2022년 D.R. Horton에 매각됐다.','GRA':'W.R. Grace는 정유·석유화학 촉매와 specialty materials를 공급하는 글로벌 특수화학사다. 2001년 asbestos liabilities를 해결하기 위해 Chapter 11을 신청한 뒤 영업은 계속했고, 법원·보험·trust 구조를 통해 legacy liabilities를 정리해 2014년 bankruptcy에서 나왔다. 따라서 equity 가치는 영업사업의 normalized EBITDA뿐 아니라 asbestos claim waterfall, cash/insurance, emergence timing과 post-emergence capital structure에 크게 좌우됐다.'}
# PICO outcomes differentiate by timing
pico={
2009:('금융위기 뒤 PICO Long은 water rights·UCP/토지 등 자산가치가 depressed market cap보다 크고, 긴 개발기간을 견디면 SOTP discount가 줄어든다는 논지로 재구성된다.','가치는 결국 실현됐지만 매우 오래 걸렸다. 2017 UCP는 Century에 매각되어 PICO가 $55.3m 현금과 약 2.4m Century 주식을 받았고, 2022 핵심 Vidler는 D.R. Horton에 $15.75/share, 약 $291m equity value로 매각됐다.','자산 방향은 맞았지만 catalyst가 늦었다. water rights는 book value가 아니라 규제·개발·buyer timing의 option asset이므로 연환산 IRR이 핵심이다.','2017 UCP monetization','2017-08-04','부분적중·긴 시간'),
2011:('2011 Long은 Vidler water assets와 UCP/real estate의 SOTP가 주가보다 높으며 scarce Southwest water의 장기 option value를 시장이 과소평가한다는 논지로 재구성된다.','UCP와 Vidler 모두 후속 매각으로 현금화됐다. 다만 2011부터 최종 Vidler exit까지 11년이 걸려 holding-company cost와 기회비용이 컸다.','NAV 할인 자체보다 NAV가 언제 현금으로 바뀌는지와 corporate burn을 반드시 IRR에 넣어야 한다.','2017 UCP monetization','2017-08-04','부분적중·타이밍 지연'),
2013:('2013 Long은 UCP 가치가 더 투명해지고 water portfolio가 장부가보다 높은 잠재가치를 지녀 asset monetization이 discount를 좁힐 수 있다는 event/SOTP 논지로 재구성된다.','2017 UCP sale은 실제 catalyst가 되었고 PICO는 현금과 Century 지분을 받았다. 이후 water-only 형태로 단순화되어 2022 최종 매각까지 이어졌다.','SOTP thesis는 맞았다. 그러나 각 자산별 exit probability×시간을 따로 할인해야 holding-company discount를 과소평가하지 않는다.','2017 UCP merger close','2017-08-04','적중·느린 실현'),
2014:('2014 Long은 공개시장 UCP 지분과 Vidler water assets를 합산한 SOTP 대비 할인, 그리고 자산매각/자본환원을 catalyst로 본 논지로 재구성된다.','2015~17 회사는 명시적으로 asset monetization 후 capital return을 우선하겠다고 전환했고 UCP 매각으로 구조가 단순화됐다. 2022 Vidler sale이 최종 exit였다.','자산가치보다 governance/capital allocation 전환이 discount closure의 결정적 catalyst였다.','2016~17 return-of-capital 정책 명시','2017-02-01','적중'),
2015:('2015 Long은 복잡한 holding structure와 agribusiness/UCP/water assets의 합계가 주가보다 크고, 비핵심자산 정리와 buyback이 value realization을 촉진한다는 논지로 재구성된다.','2015 10-K부터 회사는 monetization proceeds를 재투자보다 자본환원에 쓰는 것이 최고 수익이라고 명시했다. agribusiness가 중단사업이 되고 2017 UCP가 매각되며 thesis가 실제 corporate action으로 전환됐다.','2015는 단순 hidden asset에서 self-liquidation/capital-return thesis로 바뀐 중요한 시점이었다.','2015 return-of-capital policy','2015-12-31','적중'),
2016:('2016 Long은 governance/capital allocation 변화로 PICO가 empire-building에서 자산현금화·환원으로 전환하면 persistent SOTP discount가 축소된다는 논지로 재구성된다.','2017 회사는 asset monetization proceeds를 buyback/특별배당 등으로 환원한다고 재확인했고 UCP merger를 완료했다. 이후 Vidler 중심으로 단순화됐고 2022 전략적 매각으로 종결됐다.','holding company에서 discount 해소의 핵심은 NAV 추정 정확도보다 경영진 인센티브와 irreversible capital-return policy다.','2017 UCP sale + cost cuts','2017-08-04','적중'),
2018:('2018 Long은 UCP가 이미 매각된 뒤 사실상 Vidler water portfolio와 현금/NOL의 단순화된 asset play가 되었고, water sales·자사주·전략적 거래가 remaining discount를 닫을 수 있다는 논지로 재구성된다.','2019에도 회사는 water credits를 현금화하고 자본환원 정책을 유지했다. 2021 Vidler로 사명을 바꿨으며 2022 D.R. Horton이 $15.75/share 현금, 약 $291m에 전량 인수했다.','이 시점은 복잡성 감소로 thesis quality가 높아졌다. final buyer가 water rights를 개발에 직접 쓸 수 있는 homebuilder였다는 점이 strategic value를 입증했다.','2022 D.R. Horton agreement','2022-04-14','적중')}
# map duplicate 2015 IDs by author emphasis
O={}
for x in ideas[:8]:
 iid,date,yr,*_=x; k=2018 if yr==2018 else yr; O[iid]=pico[k]
O['3cc091ad-fd8f-4ce0-b133-43f5e20406fc']=pico[2015]
O['d80c3e42-9de6-4a0d-b44d-5b7e818b3ed6']=(pico[2015][0].replace('복잡한 holding structure','자사주·자본환원과 복잡한 holding structure'),pico[2015][1],pico[2015][2],pico[2015][3],pico[2015][4],pico[2015][5])
O['01021a69-9067-48f1-b24d-5107486b8903']=pico[2016]
O['527b25be-7a00-4303-8720-2593189c93b4']=pico[2018]
O['3ec8f243-7c36-4af5-bd2d-3976b5a8761f']=('2006 Grace Short는 이미 Chapter 11에 있던 회사의 asbestos claim 규모와 emergence dilution/liability가 equity 가치보다 클 수 있고, 영업사업 가치만 보는 시장이 contingent liabilities를 과소평가한다는 논지로 재구성된다.','Grace는 2008년에도 65,656건의 asbestos-related lawsuits와 129,191 personal-injury claims를 공시했지만 Chapter 11 process로 claims를 묶어 해결했다. 2014년 2월 3일 bankruptcy에서 공식적으로 emergence했고, 2021년 Standard Industries가 $70/share cash, 약 $7bn enterprise transaction으로 인수했다. 장기 파국 Short는 실패했다.','liability 규모만 합산하고 법적 구조가 tail liability를 trust·insurance·plan으로 ring-fence할 확률을 충분히 모델링하지 않은 것이 핵심 오류다.','2011~12 plan confirmation / appeals resolution','2012-12-31','실패')
O['b29604b6-bd7a-480e-abe7-7b0119a99194']=('2012 Grace Long은 10년 넘은 Chapter 11이 막바지에 있고, operating businesses와 약 $1.064bn DIP cash가 강한 가운데 asbestos liability가 plan을 통해 정형화되면 legal overhang 해소와 재평가가 가능하다는 event-driven thesis로 재구성된다.','2012 10-K에서 DIP cash는 $1.064bn이었다. 법원 confirmation과 appeals 해결 후 Grace는 2014년 2월 3일 Chapter 11에서 나왔다. post-emergence에는 legacy asbestos claims가 PI/PD trust로 channel되었고, 2021 Standard Industries가 $70/share cash에 인수하기로 합의했다.','legal overhang이 무한한 liability가 아니라 bounded waterfall로 바뀌는 inflection을 포착했다. bankruptcy equity는 headline claim보다 plan waterfall·cash·insurance·enterprise value를 함께 계산해야 한다.','2014 Chapter 11 emergence','2014-02-03','적중')
clP=['water asset NAV·scarcity','UCP/other asset monetization','corporate burn·tax/NOL','capital return·buyback','SOTP valuation·IRR','governance·catalyst·반증'];clG=['operating business value','asbestos claim waterfall','cash·insurance recovery','emergence capital structure','valuation·IRR','court/catalyst·반증'];w=[20,18,17,16,15,14]
st=['무슨 기업인가','산업 가치사슬과 돈의 흐름','경쟁우위·경쟁구도·핵심 지표','당시 VIC 원문과 핵심 숫자','밸류에이션과 기대수익의 연결','실제 전개','무엇이 맞았나','무엇이 틀렸나/놓쳤나','사전 반증조건과 첫 신호','재사용 가능한 교훈']
IM=[];PM=[];SE=[];CL=[];ME=[];TL=[];SO=[]
for x in ideas:
 iid,date,yr,t,co,au,direction,link=x; short=direction=='Short'; th,act,ver,first,fd,overall=O[iid]
 IM.append(dict(idea_id=iid,date=date,year=yr,ticker=t,company_name=co,author=au,direction_ko='숏' if short else '롱',is_short=short,contest_winner=1 if iid=='3ec8f243-7c36-4af5-bd2d-3976b5a8761f' else 0,source_link=link,description_chars=0,catalyst_chars=0,narrative_tags_ko='SOTP; asset monetization; event-driven; capital allocation; 심층검증',idea_type_ko='기업가치',performance_available=0,auto_tag_status_ko='수동 심층검증'))
 err='시간가치·corporate burn과 catalyst probability를 NAV에서 분리해야 했다.' if t=='PICO' and ('긴' in overall or '부분' in overall) else ('법적 claim의 gross 규모와 plan waterfall상 실제 equity burden을 구분하지 못했다.' if overall=='실패' else '핵심 catalyst는 맞았지만 각 waterfall 변수와 IRR sensitivity를 더 명시할 수 있었다.')
 lesson='SOTP는 자산가치 합계가 아니라 각 자산의 sale probability×net proceeds×time discount에서 corporate burn·tax를 차감한 realizable NAV로 본다.' if t=='PICO' else 'bankruptcy equity는 headline liabilities보다 plan waterfall, trust funding, insurance, cash, post-emergence debt와 normalized EV를 동시 모델링한다.'
 PM.append(dict(idea_id=iid,ticker=t,research_direction_ko=direction,company_description_ko=desc[t],original_thesis_ko=th,actual_development_ko=act,thesis_verdict_ko=ver,business_verdict_ko=act,catalyst_verdict_ko=first,valuation_verdict_ko='시간가치와 liability/asset realization probability를 반영한 probability-weighted NAV/EV로 판단한다.',stock_verdict_ko=overall,current_verdict_ko=act,overall_verdict_ko=overall,why_ko=ver,success_pattern_ko='asset monetization; governance catalyst; bounded legal waterfall' if overall!='실패' else '',failure_pattern_ko='gross-liability extrapolation' if overall=='실패' else '',root_error_ko=err,first_signal_ko=first,first_signal_date=fd,knowable_at_t0_ko='asset inventory, corporate cash burn, UCP stake 또는 DIP cash, asbestos insurance/plan status는 당시 공시로 추적 가능했다.',avoidability_ko='높음' if overall=='실패' else '중간',counterfactual_question_ko='5년 내 monetization/emergence가 안 되어도 현재 가격이 time-discounted realizable NAV로 지지되는가?',analyst_note_ko=f'raw is_short={str(short).lower()} 보존; research direction={direction}. 오래된 VIC 본문이 완전 재수집되지 않은 경우 thesis 서술은 raw metadata와 당시 SEC filings를 바탕으로 한 구조적 재구성이다.',corrected_return_1y=None,corrected_return_3y=None,corrected_return_5y=None,confidence=.95 if link else .9,research_asof='2026-09-05',research_status_ko='1차자료 외부검증 완료'))
 b=[desc[t],desc[t]+(' 수자원은 승인·개발·수요자 확보 후 sale proceeds가 생기므로 장부가와 현금화가 크게 시차날 수 있다.' if t=='PICO' else ' Chapter 11에서는 claims가 법원 plan과 trust funding을 거쳐 equity waterfall로 번역된다.'),'핵심은 headline growth가 아니라 scarce asset/technical franchise와 이를 현금으로 바꾸는 governance·legal process다.',th,'단순 SOTP 또는 gross claims가 아니라 time-to-cash와 probability를 적용한 expected IRR이 기준이다.',act,ver,err,f'사전 반증은 realizable NAV/plan recovery가 훼손되거나 catalyst가 반복 지연되어 연환산 IRR이 기준 이하로 떨어지는 경우다. 첫 신호: {first}.',lesson]
 for j,(a,bdy) in enumerate(zip(st,b),1):SE.append(dict(idea_id=iid,section_order=j,section_title_ko=a,section_body_ko=bdy))
 ct=clP if t=='PICO' else clG; fals=['핵심 자산/영업가치가 독립 검증치보다 하락','예상 monetization/liability waterfall이 불리하게 변경','cash burn·funding gap이 예상보다 확대','자본환원/emergence가 지연되며 dilution 증가','time-discounted expected IRR이 hurdle 미달','governance/court catalyst가 반대로 전개']
 for j,(a,ww) in enumerate(zip(ct,w),1):CL.append(dict(idea_id=iid,claim_order=j,claim_title_ko=a,thesis_weight_pct=ww,original_claim_ko=th,t0_evidence_ko='raw VIC direction/date/author와 contemporaneous SEC filings의 asset/legal/capital structure를 교차검증.',key_assumption_ko='해당 항목이 accounting value를 realizable equity cash flow로 연결한다.',ex_ante_falsifier_ko=fals[j-1],actual_result_ko=act,quantitative_gap_ko=('UCP: $55.3m cash + 2.4m Century shares; Vidler: 2022 $15.75/share, ~$291m' if t=='PICO' else ('2012 DIP cash $1.064bn; 2014 emergence; 2021 $70/share sale' if direction=='Long' else '2008 65,656 lawsuits/129,191 PI claims; 2014 emergence')),verdict_ko='오판' if overall=='실패' else ('적중' if overall=='적중' else '부분적중'),analytical_error_ko=err,reusable_lesson_ko=lesson))
 names=['water/asset realizable NAV','asset monetization proceeds','corporate cash burn','capital return / exit'] if t=='PICO' else ['normalized operating EV','asbestos claim/trust waterfall','cash & insurance','emergence / strategic exit']
 av=['2017 UCP monetized; 2022 water portfolio strategic exit','UCP $55.3m cash + shares; Vidler ~$291m','2017 cost cuts; later water-only simplification','2022 DHI $15.75/share cash'] if t=='PICO' else ['specialty chemicals survived/revalued','claims channeled to PI/PD trusts after 2014','2012 DIP cash $1.064bn; insurance disclosed','2014 emergence; 2021 $70/share Standard deal']
 for j,(n,a) in enumerate(zip(names,av),1):ME.append(dict(idea_id=iid,metric_order=j,metric_name_ko=n,t0_value_ko='당시 filing/VIC 기준',actual_value_ko=a,interpretation_ko='book/gross value보다 realizable equity cash flow와 시간가치를 검증하는 KPI.'))
 ev=[(date,'VIC idea 게시','T0 direction'),(date,'당시 asset/liability 구조 확인','base case'),(fd,first,'첫 핵심 catalyst'),('2017-08-04','UCP merger / asset simplification' if t=='PICO' else 'post-emergence operating path','intermediate update'),('2021-12-31','Vidler-only / strategic option' if t=='PICO' else 'Standard Industries $70/share transaction','late-stage update'),('2022-05-25','D.R. Horton Vidler acquisition close' if t=='PICO' else '사후 outcome 확인','최종 판정')]
 for j,(dt,e,s) in enumerate(ev,1):TL.append(dict(idea_id=iid,event_order=j,event_date=dt,event_ko=e,signal_ko=s))
 keys=['p15','p17','p17pr','p19','p21','p22'] if t=='PICO' else ['g08','g12','g14','g18','g21','g21q']
 for j,k in enumerate(keys,1):SO.append(dict(idea_id=iid,source_order=j,source_type='SEC primary filing',source_name=k,source_url=SRC[k],source_date=None,use_ko='당시 asset/liability, catalyst와 최종 outcome 검증'))
p=dict(schema_version='deep_v7',batch='033',title='PICO Holdings & W.R. Grace asset/legal-overhang postmortems',research_asof='2026-09-05',ideas_master=IM,postmortems=PM,sections=SE,claims=CL,metrics=ME,timeline=TL,sources=SO)
assert [len(p[k]) for k in ['ideas_master','postmortems','sections','claims','metrics','timeline','sources']]==[10,10,100,60,40,60,60];assert len({z['idea_id'] for z in IM})==10
for z in IM:
 iid=z['idea_id'];assert sum(q['thesis_weight_pct'] for q in CL if q['idea_id']==iid)==100;assert len([q for q in SE if q['idea_id']==iid])==10
J.parent.mkdir(parents=True,exist_ok=True);M.parent.mkdir(parents=True,exist_ok=True);J.write_text(json.dumps(p,ensure_ascii=False,indent=2),encoding='utf-8')
lines=['# Batch 033 — PICO Holdings & W.R. Grace: SOTP·자산현금화와 법적 오버행','', '> **범위:** PICO Long 8건 + GRA 2006 Short / 2012 Long 2건. raw direction은 그대로 보존했다. 오래된 VIC 본문이 완전 재수집되지 않은 경우 아래 thesis 문장은 직접인용이 아니라 raw metadata와 contemporaneous primary filings에 기반한 구조적 재구성이다.','', '## 검증 요약','','- Ideas: **10**','- Sections: **100**','- Weighted claims: **60** — idea별 **100%**','- Metrics: **40**','- Timeline items: **60**','- Sources: **60**','','## 공통 프레임','','PICO와 Grace는 모두 회계 EPS보다 **현금화 waterfall**이 중요한 투자다. PICO에서는 water/UCP 자산이 언제 얼마에 팔리고 그 현금이 shareholder에게 돌아오는지가 가치이고, Grace에서는 operating EV에서 asbestos trust funding·post-emergence debt를 차감한 뒤 equity에 무엇이 남는지가 가치다. 따라서 NAV나 gross liability를 한 시점의 숫자로 보는 대신 **확률×순현금×시간**으로 IRR을 계산해야 한다.','']
for t,label in [('PICO','PICO HOLDINGS / VIDLER'),('GRA','W.R. GRACE')]:
 lines += [f'# {label}','']
 for x in [q for q in ideas if q[3]==t]:
  iid,date,yr,t,co,au,direction,link=x;ix=ideas.index(x)+1
  lines += [f'## {ix}. {date} — {t} {direction} — {au}','',f'**원본 방향 검증:** raw `is_short={str(direction=="Short").lower()}` → **{direction}**. '+('VIC source link 보존.' if link else 'raw dataset의 direction metadata로 보존.'),'']
  for s in [q for q in SE if q['idea_id']==iid]:lines += [f"### {s['section_order']}. {s['section_title_ko']}",s['section_body_ko'],'']
  lines += ['### Claim audit','','|#|주장 축|Weight|반증조건|판정|','|---:|---|---:|---|---|']
  for c in [q for q in CL if q['idea_id']==iid]:lines += [f"|{c['claim_order']}|{c['claim_title_ko']}|{c['thesis_weight_pct']}%|{c['ex_ante_falsifier_ko']}|{c['verdict_ko']}|"]
  lines += ['','### Metric audit','','|#|Metric|T0|Actual|','|---:|---|---|---|']
  for m in [q for q in ME if q['idea_id']==iid]:lines += [f"|{m['metric_order']}|{m['metric_name_ko']}|{m['t0_value_ko']}|{m['actual_value_ko']}|"]
  lines += ['','### Timeline','','|날짜|사건|의미|','|---|---|---|']
  for a in [q for q in TL if q['idea_id']==iid]:lines += [f"|{a['event_date']}|{a['event_ko']}|{a['signal_ko']}|"]
  lines += ['','### Primary-source audit','']
  for s in [q for q in SO if q['idea_id']==iid]:lines += [f"- [{s['source_name']}]({s['source_url']}) — {s['use_ko']}"]
  lines += ['']
M.write_text('\n'.join(lines)+'\n',encoding='utf-8')
txt=REG.read_text(encoding='utf-8'); ent='    ("batch_033_pico_grace_deep_v7.json", "batch_033_pico_grace_10.md", "Batch 033"),\n';mark='    ("all_reviewed_v8_index.json", "all_reviewed_v8.md.gz", "V8 전체 DB"),\n'
if 'batch_033_pico_grace_deep_v7.json' not in txt: assert mark in txt;REG.write_text(txt.replace(mark,ent+mark),encoding='utf-8')
q=json.loads(J.read_text(encoding='utf-8'));assert len(q['claims'])==60 and len(q['sources'])==60
print('VALIDATED 033', {k:len(q[k]) for k in ['ideas_master','sections','claims','metrics','timeline','sources']})
